unit Markdown4D.Emoji.Shortcodes;

{
  The shortcode table below is derived from db/emoji.json of gemoji v4.1.0
  (https://github.com/github/gemoji). Regenerate it with
  tools/Generate-EmojiShortcodes.ps1. Every alias of an emoji that has a
  Unicode character is one entry; custom aliases without a character (such as
  octocat) are left out. Each value lists the code points of the emoji in hex.

  gemoji is distributed under the MIT license:

  Copyright (c) 2019 GitHub, Inc.

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
}

interface

type
  TEmojiShortcodes = class
  private
    class function DecodeCodePoints(const CodePoints: string): string;
  public
    class function TryDecode(const Name: string; out Emoji: string): Boolean;
    class function Count: Integer;
    class function NameAt(const Index: Integer): string;
  end;

implementation

uses
  System.SysUtils,
  System.Character;

type
  TEmojiShortcodeMapping = record
    Name: string;
    CodePoints: string;
  end;

const
  CodePointSeparator = ' ';
  HexPrefix = '$';
  ShortcodeCount = 1892;
  Shortcodes: array[0..ShortcodeCount - 1] of TEmojiShortcodeMapping = (
    (Name: '+1'; CodePoints: '1F44D'),
    (Name: '-1'; CodePoints: '1F44E'),
    (Name: '100'; CodePoints: '1F4AF'),
    (Name: '1234'; CodePoints: '1F522'),
    (Name: '1st_place_medal'; CodePoints: '1F947'),
    (Name: '2nd_place_medal'; CodePoints: '1F948'),
    (Name: '3rd_place_medal'; CodePoints: '1F949'),
    (Name: '8ball'; CodePoints: '1F3B1'),
    (Name: 'a'; CodePoints: '1F170 FE0F'),
    (Name: 'ab'; CodePoints: '1F18E'),
    (Name: 'abacus'; CodePoints: '1F9EE'),
    (Name: 'abc'; CodePoints: '1F524'),
    (Name: 'abcd'; CodePoints: '1F521'),
    (Name: 'accept'; CodePoints: '1F251'),
    (Name: 'accordion'; CodePoints: '1FA97'),
    (Name: 'adhesive_bandage'; CodePoints: '1FA79'),
    (Name: 'adult'; CodePoints: '1F9D1'),
    (Name: 'aerial_tramway'; CodePoints: '1F6A1'),
    (Name: 'afghanistan'; CodePoints: '1F1E6 1F1EB'),
    (Name: 'airplane'; CodePoints: '2708 FE0F'),
    (Name: 'aland_islands'; CodePoints: '1F1E6 1F1FD'),
    (Name: 'alarm_clock'; CodePoints: '23F0'),
    (Name: 'albania'; CodePoints: '1F1E6 1F1F1'),
    (Name: 'alembic'; CodePoints: '2697 FE0F'),
    (Name: 'algeria'; CodePoints: '1F1E9 1F1FF'),
    (Name: 'alien'; CodePoints: '1F47D'),
    (Name: 'ambulance'; CodePoints: '1F691'),
    (Name: 'american_samoa'; CodePoints: '1F1E6 1F1F8'),
    (Name: 'amphora'; CodePoints: '1F3FA'),
    (Name: 'anatomical_heart'; CodePoints: '1FAC0'),
    (Name: 'anchor'; CodePoints: '2693'),
    (Name: 'andorra'; CodePoints: '1F1E6 1F1E9'),
    (Name: 'angel'; CodePoints: '1F47C'),
    (Name: 'anger'; CodePoints: '1F4A2'),
    (Name: 'angola'; CodePoints: '1F1E6 1F1F4'),
    (Name: 'angry'; CodePoints: '1F620'),
    (Name: 'anguilla'; CodePoints: '1F1E6 1F1EE'),
    (Name: 'anguished'; CodePoints: '1F627'),
    (Name: 'ant'; CodePoints: '1F41C'),
    (Name: 'antarctica'; CodePoints: '1F1E6 1F1F6'),
    (Name: 'antigua_barbuda'; CodePoints: '1F1E6 1F1EC'),
    (Name: 'apple'; CodePoints: '1F34E'),
    (Name: 'aquarius'; CodePoints: '2652'),
    (Name: 'argentina'; CodePoints: '1F1E6 1F1F7'),
    (Name: 'aries'; CodePoints: '2648'),
    (Name: 'armenia'; CodePoints: '1F1E6 1F1F2'),
    (Name: 'arrow_backward'; CodePoints: '25C0 FE0F'),
    (Name: 'arrow_double_down'; CodePoints: '23EC'),
    (Name: 'arrow_double_up'; CodePoints: '23EB'),
    (Name: 'arrow_down'; CodePoints: '2B07 FE0F'),
    (Name: 'arrow_down_small'; CodePoints: '1F53D'),
    (Name: 'arrow_forward'; CodePoints: '25B6 FE0F'),
    (Name: 'arrow_heading_down'; CodePoints: '2935 FE0F'),
    (Name: 'arrow_heading_up'; CodePoints: '2934 FE0F'),
    (Name: 'arrow_left'; CodePoints: '2B05 FE0F'),
    (Name: 'arrow_lower_left'; CodePoints: '2199 FE0F'),
    (Name: 'arrow_lower_right'; CodePoints: '2198 FE0F'),
    (Name: 'arrow_right'; CodePoints: '27A1 FE0F'),
    (Name: 'arrow_right_hook'; CodePoints: '21AA FE0F'),
    (Name: 'arrow_up'; CodePoints: '2B06 FE0F'),
    (Name: 'arrow_up_down'; CodePoints: '2195 FE0F'),
    (Name: 'arrow_up_small'; CodePoints: '1F53C'),
    (Name: 'arrow_upper_left'; CodePoints: '2196 FE0F'),
    (Name: 'arrow_upper_right'; CodePoints: '2197 FE0F'),
    (Name: 'arrows_clockwise'; CodePoints: '1F503'),
    (Name: 'arrows_counterclockwise'; CodePoints: '1F504'),
    (Name: 'art'; CodePoints: '1F3A8'),
    (Name: 'articulated_lorry'; CodePoints: '1F69B'),
    (Name: 'artificial_satellite'; CodePoints: '1F6F0 FE0F'),
    (Name: 'artist'; CodePoints: '1F9D1 200D 1F3A8'),
    (Name: 'aruba'; CodePoints: '1F1E6 1F1FC'),
    (Name: 'ascension_island'; CodePoints: '1F1E6 1F1E8'),
    (Name: 'asterisk'; CodePoints: '002A FE0F 20E3'),
    (Name: 'astonished'; CodePoints: '1F632'),
    (Name: 'astronaut'; CodePoints: '1F9D1 200D 1F680'),
    (Name: 'athletic_shoe'; CodePoints: '1F45F'),
    (Name: 'atm'; CodePoints: '1F3E7'),
    (Name: 'atom_symbol'; CodePoints: '269B FE0F'),
    (Name: 'australia'; CodePoints: '1F1E6 1F1FA'),
    (Name: 'austria'; CodePoints: '1F1E6 1F1F9'),
    (Name: 'auto_rickshaw'; CodePoints: '1F6FA'),
    (Name: 'avocado'; CodePoints: '1F951'),
    (Name: 'axe'; CodePoints: '1FA93'),
    (Name: 'azerbaijan'; CodePoints: '1F1E6 1F1FF'),
    (Name: 'b'; CodePoints: '1F171 FE0F'),
    (Name: 'baby'; CodePoints: '1F476'),
    (Name: 'baby_bottle'; CodePoints: '1F37C'),
    (Name: 'baby_chick'; CodePoints: '1F424'),
    (Name: 'baby_symbol'; CodePoints: '1F6BC'),
    (Name: 'back'; CodePoints: '1F519'),
    (Name: 'bacon'; CodePoints: '1F953'),
    (Name: 'badger'; CodePoints: '1F9A1'),
    (Name: 'badminton'; CodePoints: '1F3F8'),
    (Name: 'bagel'; CodePoints: '1F96F'),
    (Name: 'baggage_claim'; CodePoints: '1F6C4'),
    (Name: 'baguette_bread'; CodePoints: '1F956'),
    (Name: 'bahamas'; CodePoints: '1F1E7 1F1F8'),
    (Name: 'bahrain'; CodePoints: '1F1E7 1F1ED'),
    (Name: 'balance_scale'; CodePoints: '2696 FE0F'),
    (Name: 'bald_man'; CodePoints: '1F468 200D 1F9B2'),
    (Name: 'bald_woman'; CodePoints: '1F469 200D 1F9B2'),
    (Name: 'ballet_shoes'; CodePoints: '1FA70'),
    (Name: 'balloon'; CodePoints: '1F388'),
    (Name: 'ballot_box'; CodePoints: '1F5F3 FE0F'),
    (Name: 'ballot_box_with_check'; CodePoints: '2611 FE0F'),
    (Name: 'bamboo'; CodePoints: '1F38D'),
    (Name: 'banana'; CodePoints: '1F34C'),
    (Name: 'bangbang'; CodePoints: '203C FE0F'),
    (Name: 'bangladesh'; CodePoints: '1F1E7 1F1E9'),
    (Name: 'banjo'; CodePoints: '1FA95'),
    (Name: 'bank'; CodePoints: '1F3E6'),
    (Name: 'bar_chart'; CodePoints: '1F4CA'),
    (Name: 'barbados'; CodePoints: '1F1E7 1F1E7'),
    (Name: 'barber'; CodePoints: '1F488'),
    (Name: 'baseball'; CodePoints: '26BE'),
    (Name: 'basket'; CodePoints: '1F9FA'),
    (Name: 'basketball'; CodePoints: '1F3C0'),
    (Name: 'basketball_man'; CodePoints: '26F9 FE0F 200D 2642 FE0F'),
    (Name: 'basketball_woman'; CodePoints: '26F9 FE0F 200D 2640 FE0F'),
    (Name: 'bat'; CodePoints: '1F987'),
    (Name: 'bath'; CodePoints: '1F6C0'),
    (Name: 'bathtub'; CodePoints: '1F6C1'),
    (Name: 'battery'; CodePoints: '1F50B'),
    (Name: 'beach_umbrella'; CodePoints: '1F3D6 FE0F'),
    (Name: 'beans'; CodePoints: '1FAD8'),
    (Name: 'bear'; CodePoints: '1F43B'),
    (Name: 'bearded_person'; CodePoints: '1F9D4'),
    (Name: 'beaver'; CodePoints: '1F9AB'),
    (Name: 'bed'; CodePoints: '1F6CF FE0F'),
    (Name: 'bee'; CodePoints: '1F41D'),
    (Name: 'beer'; CodePoints: '1F37A'),
    (Name: 'beers'; CodePoints: '1F37B'),
    (Name: 'beetle'; CodePoints: '1FAB2'),
    (Name: 'beginner'; CodePoints: '1F530'),
    (Name: 'belarus'; CodePoints: '1F1E7 1F1FE'),
    (Name: 'belgium'; CodePoints: '1F1E7 1F1EA'),
    (Name: 'belize'; CodePoints: '1F1E7 1F1FF'),
    (Name: 'bell'; CodePoints: '1F514'),
    (Name: 'bell_pepper'; CodePoints: '1FAD1'),
    (Name: 'bellhop_bell'; CodePoints: '1F6CE FE0F'),
    (Name: 'benin'; CodePoints: '1F1E7 1F1EF'),
    (Name: 'bento'; CodePoints: '1F371'),
    (Name: 'bermuda'; CodePoints: '1F1E7 1F1F2'),
    (Name: 'beverage_box'; CodePoints: '1F9C3'),
    (Name: 'bhutan'; CodePoints: '1F1E7 1F1F9'),
    (Name: 'bicyclist'; CodePoints: '1F6B4'),
    (Name: 'bike'; CodePoints: '1F6B2'),
    (Name: 'biking_man'; CodePoints: '1F6B4 200D 2642 FE0F'),
    (Name: 'biking_woman'; CodePoints: '1F6B4 200D 2640 FE0F'),
    (Name: 'bikini'; CodePoints: '1F459'),
    (Name: 'billed_cap'; CodePoints: '1F9E2'),
    (Name: 'biohazard'; CodePoints: '2623 FE0F'),
    (Name: 'bird'; CodePoints: '1F426'),
    (Name: 'birthday'; CodePoints: '1F382'),
    (Name: 'bison'; CodePoints: '1F9AC'),
    (Name: 'biting_lip'; CodePoints: '1FAE6'),
    (Name: 'black_cat'; CodePoints: '1F408 200D 2B1B'),
    (Name: 'black_circle'; CodePoints: '26AB'),
    (Name: 'black_flag'; CodePoints: '1F3F4'),
    (Name: 'black_heart'; CodePoints: '1F5A4'),
    (Name: 'black_joker'; CodePoints: '1F0CF'),
    (Name: 'black_large_square'; CodePoints: '2B1B'),
    (Name: 'black_medium_small_square'; CodePoints: '25FE'),
    (Name: 'black_medium_square'; CodePoints: '25FC FE0F'),
    (Name: 'black_nib'; CodePoints: '2712 FE0F'),
    (Name: 'black_small_square'; CodePoints: '25AA FE0F'),
    (Name: 'black_square_button'; CodePoints: '1F532'),
    (Name: 'blond_haired_man'; CodePoints: '1F471 200D 2642 FE0F'),
    (Name: 'blond_haired_person'; CodePoints: '1F471'),
    (Name: 'blond_haired_woman'; CodePoints: '1F471 200D 2640 FE0F'),
    (Name: 'blonde_woman'; CodePoints: '1F471 200D 2640 FE0F'),
    (Name: 'blossom'; CodePoints: '1F33C'),
    (Name: 'blowfish'; CodePoints: '1F421'),
    (Name: 'blue_book'; CodePoints: '1F4D8'),
    (Name: 'blue_car'; CodePoints: '1F699'),
    (Name: 'blue_heart'; CodePoints: '1F499'),
    (Name: 'blue_square'; CodePoints: '1F7E6'),
    (Name: 'blueberries'; CodePoints: '1FAD0'),
    (Name: 'blush'; CodePoints: '1F60A'),
    (Name: 'boar'; CodePoints: '1F417'),
    (Name: 'boat'; CodePoints: '26F5'),
    (Name: 'bolivia'; CodePoints: '1F1E7 1F1F4'),
    (Name: 'bomb'; CodePoints: '1F4A3'),
    (Name: 'bone'; CodePoints: '1F9B4'),
    (Name: 'book'; CodePoints: '1F4D6'),
    (Name: 'bookmark'; CodePoints: '1F516'),
    (Name: 'bookmark_tabs'; CodePoints: '1F4D1'),
    (Name: 'books'; CodePoints: '1F4DA'),
    (Name: 'boom'; CodePoints: '1F4A5'),
    (Name: 'boomerang'; CodePoints: '1FA83'),
    (Name: 'boot'; CodePoints: '1F462'),
    (Name: 'bosnia_herzegovina'; CodePoints: '1F1E7 1F1E6'),
    (Name: 'botswana'; CodePoints: '1F1E7 1F1FC'),
    (Name: 'bouncing_ball_man'; CodePoints: '26F9 FE0F 200D 2642 FE0F'),
    (Name: 'bouncing_ball_person'; CodePoints: '26F9 FE0F'),
    (Name: 'bouncing_ball_woman'; CodePoints: '26F9 FE0F 200D 2640 FE0F'),
    (Name: 'bouquet'; CodePoints: '1F490'),
    (Name: 'bouvet_island'; CodePoints: '1F1E7 1F1FB'),
    (Name: 'bow'; CodePoints: '1F647'),
    (Name: 'bow_and_arrow'; CodePoints: '1F3F9'),
    (Name: 'bowing_man'; CodePoints: '1F647 200D 2642 FE0F'),
    (Name: 'bowing_woman'; CodePoints: '1F647 200D 2640 FE0F'),
    (Name: 'bowl_with_spoon'; CodePoints: '1F963'),
    (Name: 'bowling'; CodePoints: '1F3B3'),
    (Name: 'boxing_glove'; CodePoints: '1F94A'),
    (Name: 'boy'; CodePoints: '1F466'),
    (Name: 'brain'; CodePoints: '1F9E0'),
    (Name: 'brazil'; CodePoints: '1F1E7 1F1F7'),
    (Name: 'bread'; CodePoints: '1F35E'),
    (Name: 'breast_feeding'; CodePoints: '1F931'),
    (Name: 'bricks'; CodePoints: '1F9F1'),
    (Name: 'bride_with_veil'; CodePoints: '1F470 200D 2640 FE0F'),
    (Name: 'bridge_at_night'; CodePoints: '1F309'),
    (Name: 'briefcase'; CodePoints: '1F4BC'),
    (Name: 'british_indian_ocean_territory'; CodePoints: '1F1EE 1F1F4'),
    (Name: 'british_virgin_islands'; CodePoints: '1F1FB 1F1EC'),
    (Name: 'broccoli'; CodePoints: '1F966'),
    (Name: 'broken_heart'; CodePoints: '1F494'),
    (Name: 'broom'; CodePoints: '1F9F9'),
    (Name: 'brown_circle'; CodePoints: '1F7E4'),
    (Name: 'brown_heart'; CodePoints: '1F90E'),
    (Name: 'brown_square'; CodePoints: '1F7EB'),
    (Name: 'brunei'; CodePoints: '1F1E7 1F1F3'),
    (Name: 'bubble_tea'; CodePoints: '1F9CB'),
    (Name: 'bubbles'; CodePoints: '1FAE7'),
    (Name: 'bucket'; CodePoints: '1FAA3'),
    (Name: 'bug'; CodePoints: '1F41B'),
    (Name: 'building_construction'; CodePoints: '1F3D7 FE0F'),
    (Name: 'bulb'; CodePoints: '1F4A1'),
    (Name: 'bulgaria'; CodePoints: '1F1E7 1F1EC'),
    (Name: 'bullettrain_front'; CodePoints: '1F685'),
    (Name: 'bullettrain_side'; CodePoints: '1F684'),
    (Name: 'burkina_faso'; CodePoints: '1F1E7 1F1EB'),
    (Name: 'burrito'; CodePoints: '1F32F'),
    (Name: 'burundi'; CodePoints: '1F1E7 1F1EE'),
    (Name: 'bus'; CodePoints: '1F68C'),
    (Name: 'business_suit_levitating'; CodePoints: '1F574 FE0F'),
    (Name: 'busstop'; CodePoints: '1F68F'),
    (Name: 'bust_in_silhouette'; CodePoints: '1F464'),
    (Name: 'busts_in_silhouette'; CodePoints: '1F465'),
    (Name: 'butter'; CodePoints: '1F9C8'),
    (Name: 'butterfly'; CodePoints: '1F98B'),
    (Name: 'cactus'; CodePoints: '1F335'),
    (Name: 'cake'; CodePoints: '1F370'),
    (Name: 'calendar'; CodePoints: '1F4C6'),
    (Name: 'call_me_hand'; CodePoints: '1F919'),
    (Name: 'calling'; CodePoints: '1F4F2'),
    (Name: 'cambodia'; CodePoints: '1F1F0 1F1ED'),
    (Name: 'camel'; CodePoints: '1F42B'),
    (Name: 'camera'; CodePoints: '1F4F7'),
    (Name: 'camera_flash'; CodePoints: '1F4F8'),
    (Name: 'cameroon'; CodePoints: '1F1E8 1F1F2'),
    (Name: 'camping'; CodePoints: '1F3D5 FE0F'),
    (Name: 'canada'; CodePoints: '1F1E8 1F1E6'),
    (Name: 'canary_islands'; CodePoints: '1F1EE 1F1E8'),
    (Name: 'cancer'; CodePoints: '264B'),
    (Name: 'candle'; CodePoints: '1F56F FE0F'),
    (Name: 'candy'; CodePoints: '1F36C'),
    (Name: 'canned_food'; CodePoints: '1F96B'),
    (Name: 'canoe'; CodePoints: '1F6F6'),
    (Name: 'cape_verde'; CodePoints: '1F1E8 1F1FB'),
    (Name: 'capital_abcd'; CodePoints: '1F520'),
    (Name: 'capricorn'; CodePoints: '2651'),
    (Name: 'car'; CodePoints: '1F697'),
    (Name: 'card_file_box'; CodePoints: '1F5C3 FE0F'),
    (Name: 'card_index'; CodePoints: '1F4C7'),
    (Name: 'card_index_dividers'; CodePoints: '1F5C2 FE0F'),
    (Name: 'caribbean_netherlands'; CodePoints: '1F1E7 1F1F6'),
    (Name: 'carousel_horse'; CodePoints: '1F3A0'),
    (Name: 'carpentry_saw'; CodePoints: '1FA9A'),
    (Name: 'carrot'; CodePoints: '1F955'),
    (Name: 'cartwheeling'; CodePoints: '1F938'),
    (Name: 'cat'; CodePoints: '1F431'),
    (Name: 'cat2'; CodePoints: '1F408'),
    (Name: 'cayman_islands'; CodePoints: '1F1F0 1F1FE'),
    (Name: 'cd'; CodePoints: '1F4BF'),
    (Name: 'central_african_republic'; CodePoints: '1F1E8 1F1EB'),
    (Name: 'ceuta_melilla'; CodePoints: '1F1EA 1F1E6'),
    (Name: 'chad'; CodePoints: '1F1F9 1F1E9'),
    (Name: 'chains'; CodePoints: '26D3 FE0F'),
    (Name: 'chair'; CodePoints: '1FA91'),
    (Name: 'champagne'; CodePoints: '1F37E'),
    (Name: 'chart'; CodePoints: '1F4B9'),
    (Name: 'chart_with_downwards_trend'; CodePoints: '1F4C9'),
    (Name: 'chart_with_upwards_trend'; CodePoints: '1F4C8'),
    (Name: 'checkered_flag'; CodePoints: '1F3C1'),
    (Name: 'cheese'; CodePoints: '1F9C0'),
    (Name: 'cherries'; CodePoints: '1F352'),
    (Name: 'cherry_blossom'; CodePoints: '1F338'),
    (Name: 'chess_pawn'; CodePoints: '265F FE0F'),
    (Name: 'chestnut'; CodePoints: '1F330'),
    (Name: 'chicken'; CodePoints: '1F414'),
    (Name: 'child'; CodePoints: '1F9D2'),
    (Name: 'children_crossing'; CodePoints: '1F6B8'),
    (Name: 'chile'; CodePoints: '1F1E8 1F1F1'),
    (Name: 'chipmunk'; CodePoints: '1F43F FE0F'),
    (Name: 'chocolate_bar'; CodePoints: '1F36B'),
    (Name: 'chopsticks'; CodePoints: '1F962'),
    (Name: 'christmas_island'; CodePoints: '1F1E8 1F1FD'),
    (Name: 'christmas_tree'; CodePoints: '1F384'),
    (Name: 'church'; CodePoints: '26EA'),
    (Name: 'cinema'; CodePoints: '1F3A6'),
    (Name: 'circus_tent'; CodePoints: '1F3AA'),
    (Name: 'city_sunrise'; CodePoints: '1F307'),
    (Name: 'city_sunset'; CodePoints: '1F306'),
    (Name: 'cityscape'; CodePoints: '1F3D9 FE0F'),
    (Name: 'cl'; CodePoints: '1F191'),
    (Name: 'clamp'; CodePoints: '1F5DC FE0F'),
    (Name: 'clap'; CodePoints: '1F44F'),
    (Name: 'clapper'; CodePoints: '1F3AC'),
    (Name: 'classical_building'; CodePoints: '1F3DB FE0F'),
    (Name: 'climbing'; CodePoints: '1F9D7'),
    (Name: 'climbing_man'; CodePoints: '1F9D7 200D 2642 FE0F'),
    (Name: 'climbing_woman'; CodePoints: '1F9D7 200D 2640 FE0F'),
    (Name: 'clinking_glasses'; CodePoints: '1F942'),
    (Name: 'clipboard'; CodePoints: '1F4CB'),
    (Name: 'clipperton_island'; CodePoints: '1F1E8 1F1F5'),
    (Name: 'clock1'; CodePoints: '1F550'),
    (Name: 'clock10'; CodePoints: '1F559'),
    (Name: 'clock1030'; CodePoints: '1F565'),
    (Name: 'clock11'; CodePoints: '1F55A'),
    (Name: 'clock1130'; CodePoints: '1F566'),
    (Name: 'clock12'; CodePoints: '1F55B'),
    (Name: 'clock1230'; CodePoints: '1F567'),
    (Name: 'clock130'; CodePoints: '1F55C'),
    (Name: 'clock2'; CodePoints: '1F551'),
    (Name: 'clock230'; CodePoints: '1F55D'),
    (Name: 'clock3'; CodePoints: '1F552'),
    (Name: 'clock330'; CodePoints: '1F55E'),
    (Name: 'clock4'; CodePoints: '1F553'),
    (Name: 'clock430'; CodePoints: '1F55F'),
    (Name: 'clock5'; CodePoints: '1F554'),
    (Name: 'clock530'; CodePoints: '1F560'),
    (Name: 'clock6'; CodePoints: '1F555'),
    (Name: 'clock630'; CodePoints: '1F561'),
    (Name: 'clock7'; CodePoints: '1F556'),
    (Name: 'clock730'; CodePoints: '1F562'),
    (Name: 'clock8'; CodePoints: '1F557'),
    (Name: 'clock830'; CodePoints: '1F563'),
    (Name: 'clock9'; CodePoints: '1F558'),
    (Name: 'clock930'; CodePoints: '1F564'),
    (Name: 'closed_book'; CodePoints: '1F4D5'),
    (Name: 'closed_lock_with_key'; CodePoints: '1F510'),
    (Name: 'closed_umbrella'; CodePoints: '1F302'),
    (Name: 'cloud'; CodePoints: '2601 FE0F'),
    (Name: 'cloud_with_lightning'; CodePoints: '1F329 FE0F'),
    (Name: 'cloud_with_lightning_and_rain'; CodePoints: '26C8 FE0F'),
    (Name: 'cloud_with_rain'; CodePoints: '1F327 FE0F'),
    (Name: 'cloud_with_snow'; CodePoints: '1F328 FE0F'),
    (Name: 'clown_face'; CodePoints: '1F921'),
    (Name: 'clubs'; CodePoints: '2663 FE0F'),
    (Name: 'cn'; CodePoints: '1F1E8 1F1F3'),
    (Name: 'coat'; CodePoints: '1F9E5'),
    (Name: 'cockroach'; CodePoints: '1FAB3'),
    (Name: 'cocktail'; CodePoints: '1F378'),
    (Name: 'coconut'; CodePoints: '1F965'),
    (Name: 'cocos_islands'; CodePoints: '1F1E8 1F1E8'),
    (Name: 'coffee'; CodePoints: '2615'),
    (Name: 'coffin'; CodePoints: '26B0 FE0F'),
    (Name: 'coin'; CodePoints: '1FA99'),
    (Name: 'cold_face'; CodePoints: '1F976'),
    (Name: 'cold_sweat'; CodePoints: '1F630'),
    (Name: 'collision'; CodePoints: '1F4A5'),
    (Name: 'colombia'; CodePoints: '1F1E8 1F1F4'),
    (Name: 'comet'; CodePoints: '2604 FE0F'),
    (Name: 'comoros'; CodePoints: '1F1F0 1F1F2'),
    (Name: 'compass'; CodePoints: '1F9ED'),
    (Name: 'computer'; CodePoints: '1F4BB'),
    (Name: 'computer_mouse'; CodePoints: '1F5B1 FE0F'),
    (Name: 'confetti_ball'; CodePoints: '1F38A'),
    (Name: 'confounded'; CodePoints: '1F616'),
    (Name: 'confused'; CodePoints: '1F615'),
    (Name: 'congo_brazzaville'; CodePoints: '1F1E8 1F1EC'),
    (Name: 'congo_kinshasa'; CodePoints: '1F1E8 1F1E9'),
    (Name: 'congratulations'; CodePoints: '3297 FE0F'),
    (Name: 'construction'; CodePoints: '1F6A7'),
    (Name: 'construction_worker'; CodePoints: '1F477'),
    (Name: 'construction_worker_man'; CodePoints: '1F477 200D 2642 FE0F'),
    (Name: 'construction_worker_woman'; CodePoints: '1F477 200D 2640 FE0F'),
    (Name: 'control_knobs'; CodePoints: '1F39B FE0F'),
    (Name: 'convenience_store'; CodePoints: '1F3EA'),
    (Name: 'cook'; CodePoints: '1F9D1 200D 1F373'),
    (Name: 'cook_islands'; CodePoints: '1F1E8 1F1F0'),
    (Name: 'cookie'; CodePoints: '1F36A'),
    (Name: 'cool'; CodePoints: '1F192'),
    (Name: 'cop'; CodePoints: '1F46E'),
    (Name: 'copyright'; CodePoints: '00A9 FE0F'),
    (Name: 'coral'; CodePoints: '1FAB8'),
    (Name: 'corn'; CodePoints: '1F33D'),
    (Name: 'costa_rica'; CodePoints: '1F1E8 1F1F7'),
    (Name: 'cote_divoire'; CodePoints: '1F1E8 1F1EE'),
    (Name: 'couch_and_lamp'; CodePoints: '1F6CB FE0F'),
    (Name: 'couple'; CodePoints: '1F46B'),
    (Name: 'couple_with_heart'; CodePoints: '1F491'),
    (Name: 'couple_with_heart_man_man'; CodePoints: '1F468 200D 2764 FE0F 200D 1F468'),
    (Name: 'couple_with_heart_woman_man'; CodePoints: '1F469 200D 2764 FE0F 200D 1F468'),
    (Name: 'couple_with_heart_woman_woman'; CodePoints: '1F469 200D 2764 FE0F 200D 1F469'),
    (Name: 'couplekiss'; CodePoints: '1F48F'),
    (Name: 'couplekiss_man_man'; CodePoints: '1F468 200D 2764 FE0F 200D 1F48B 200D 1F468'),
    (Name: 'couplekiss_man_woman'; CodePoints: '1F469 200D 2764 FE0F 200D 1F48B 200D 1F468'),
    (Name: 'couplekiss_woman_woman'; CodePoints: '1F469 200D 2764 FE0F 200D 1F48B 200D 1F469'),
    (Name: 'cow'; CodePoints: '1F42E'),
    (Name: 'cow2'; CodePoints: '1F404'),
    (Name: 'cowboy_hat_face'; CodePoints: '1F920'),
    (Name: 'crab'; CodePoints: '1F980'),
    (Name: 'crayon'; CodePoints: '1F58D FE0F'),
    (Name: 'credit_card'; CodePoints: '1F4B3'),
    (Name: 'crescent_moon'; CodePoints: '1F319'),
    (Name: 'cricket'; CodePoints: '1F997'),
    (Name: 'cricket_game'; CodePoints: '1F3CF'),
    (Name: 'croatia'; CodePoints: '1F1ED 1F1F7'),
    (Name: 'crocodile'; CodePoints: '1F40A'),
    (Name: 'croissant'; CodePoints: '1F950'),
    (Name: 'crossed_fingers'; CodePoints: '1F91E'),
    (Name: 'crossed_flags'; CodePoints: '1F38C'),
    (Name: 'crossed_swords'; CodePoints: '2694 FE0F'),
    (Name: 'crown'; CodePoints: '1F451'),
    (Name: 'crutch'; CodePoints: '1FA7C'),
    (Name: 'cry'; CodePoints: '1F622'),
    (Name: 'crying_cat_face'; CodePoints: '1F63F'),
    (Name: 'crystal_ball'; CodePoints: '1F52E'),
    (Name: 'cuba'; CodePoints: '1F1E8 1F1FA'),
    (Name: 'cucumber'; CodePoints: '1F952'),
    (Name: 'cup_with_straw'; CodePoints: '1F964'),
    (Name: 'cupcake'; CodePoints: '1F9C1'),
    (Name: 'cupid'; CodePoints: '1F498'),
    (Name: 'curacao'; CodePoints: '1F1E8 1F1FC'),
    (Name: 'curling_stone'; CodePoints: '1F94C'),
    (Name: 'curly_haired_man'; CodePoints: '1F468 200D 1F9B1'),
    (Name: 'curly_haired_woman'; CodePoints: '1F469 200D 1F9B1'),
    (Name: 'curly_loop'; CodePoints: '27B0'),
    (Name: 'currency_exchange'; CodePoints: '1F4B1'),
    (Name: 'curry'; CodePoints: '1F35B'),
    (Name: 'cursing_face'; CodePoints: '1F92C'),
    (Name: 'custard'; CodePoints: '1F36E'),
    (Name: 'customs'; CodePoints: '1F6C3'),
    (Name: 'cut_of_meat'; CodePoints: '1F969'),
    (Name: 'cyclone'; CodePoints: '1F300'),
    (Name: 'cyprus'; CodePoints: '1F1E8 1F1FE'),
    (Name: 'czech_republic'; CodePoints: '1F1E8 1F1FF'),
    (Name: 'dagger'; CodePoints: '1F5E1 FE0F'),
    (Name: 'dancer'; CodePoints: '1F483'),
    (Name: 'dancers'; CodePoints: '1F46F'),
    (Name: 'dancing_men'; CodePoints: '1F46F 200D 2642 FE0F'),
    (Name: 'dancing_women'; CodePoints: '1F46F 200D 2640 FE0F'),
    (Name: 'dango'; CodePoints: '1F361'),
    (Name: 'dark_sunglasses'; CodePoints: '1F576 FE0F'),
    (Name: 'dart'; CodePoints: '1F3AF'),
    (Name: 'dash'; CodePoints: '1F4A8'),
    (Name: 'date'; CodePoints: '1F4C5'),
    (Name: 'de'; CodePoints: '1F1E9 1F1EA'),
    (Name: 'deaf_man'; CodePoints: '1F9CF 200D 2642 FE0F'),
    (Name: 'deaf_person'; CodePoints: '1F9CF'),
    (Name: 'deaf_woman'; CodePoints: '1F9CF 200D 2640 FE0F'),
    (Name: 'deciduous_tree'; CodePoints: '1F333'),
    (Name: 'deer'; CodePoints: '1F98C'),
    (Name: 'denmark'; CodePoints: '1F1E9 1F1F0'),
    (Name: 'department_store'; CodePoints: '1F3EC'),
    (Name: 'derelict_house'; CodePoints: '1F3DA FE0F'),
    (Name: 'desert'; CodePoints: '1F3DC FE0F'),
    (Name: 'desert_island'; CodePoints: '1F3DD FE0F'),
    (Name: 'desktop_computer'; CodePoints: '1F5A5 FE0F'),
    (Name: 'detective'; CodePoints: '1F575 FE0F'),
    (Name: 'diamond_shape_with_a_dot_inside'; CodePoints: '1F4A0'),
    (Name: 'diamonds'; CodePoints: '2666 FE0F'),
    (Name: 'diego_garcia'; CodePoints: '1F1E9 1F1EC'),
    (Name: 'disappointed'; CodePoints: '1F61E'),
    (Name: 'disappointed_relieved'; CodePoints: '1F625'),
    (Name: 'disguised_face'; CodePoints: '1F978'),
    (Name: 'diving_mask'; CodePoints: '1F93F'),
    (Name: 'diya_lamp'; CodePoints: '1FA94'),
    (Name: 'dizzy'; CodePoints: '1F4AB'),
    (Name: 'dizzy_face'; CodePoints: '1F635'),
    (Name: 'djibouti'; CodePoints: '1F1E9 1F1EF'),
    (Name: 'dna'; CodePoints: '1F9EC'),
    (Name: 'do_not_litter'; CodePoints: '1F6AF'),
    (Name: 'dodo'; CodePoints: '1F9A4'),
    (Name: 'dog'; CodePoints: '1F436'),
    (Name: 'dog2'; CodePoints: '1F415'),
    (Name: 'dollar'; CodePoints: '1F4B5'),
    (Name: 'dolls'; CodePoints: '1F38E'),
    (Name: 'dolphin'; CodePoints: '1F42C'),
    (Name: 'dominica'; CodePoints: '1F1E9 1F1F2'),
    (Name: 'dominican_republic'; CodePoints: '1F1E9 1F1F4'),
    (Name: 'door'; CodePoints: '1F6AA'),
    (Name: 'dotted_line_face'; CodePoints: '1FAE5'),
    (Name: 'doughnut'; CodePoints: '1F369'),
    (Name: 'dove'; CodePoints: '1F54A FE0F'),
    (Name: 'dragon'; CodePoints: '1F409'),
    (Name: 'dragon_face'; CodePoints: '1F432'),
    (Name: 'dress'; CodePoints: '1F457'),
    (Name: 'dromedary_camel'; CodePoints: '1F42A'),
    (Name: 'drooling_face'; CodePoints: '1F924'),
    (Name: 'drop_of_blood'; CodePoints: '1FA78'),
    (Name: 'droplet'; CodePoints: '1F4A7'),
    (Name: 'drum'; CodePoints: '1F941'),
    (Name: 'duck'; CodePoints: '1F986'),
    (Name: 'dumpling'; CodePoints: '1F95F'),
    (Name: 'dvd'; CodePoints: '1F4C0'),
    (Name: 'e-mail'; CodePoints: '1F4E7'),
    (Name: 'eagle'; CodePoints: '1F985'),
    (Name: 'ear'; CodePoints: '1F442'),
    (Name: 'ear_of_rice'; CodePoints: '1F33E'),
    (Name: 'ear_with_hearing_aid'; CodePoints: '1F9BB'),
    (Name: 'earth_africa'; CodePoints: '1F30D'),
    (Name: 'earth_americas'; CodePoints: '1F30E'),
    (Name: 'earth_asia'; CodePoints: '1F30F'),
    (Name: 'ecuador'; CodePoints: '1F1EA 1F1E8'),
    (Name: 'egg'; CodePoints: '1F95A'),
    (Name: 'eggplant'; CodePoints: '1F346'),
    (Name: 'egypt'; CodePoints: '1F1EA 1F1EC'),
    (Name: 'eight'; CodePoints: '0038 FE0F 20E3'),
    (Name: 'eight_pointed_black_star'; CodePoints: '2734 FE0F'),
    (Name: 'eight_spoked_asterisk'; CodePoints: '2733 FE0F'),
    (Name: 'eject_button'; CodePoints: '23CF FE0F'),
    (Name: 'el_salvador'; CodePoints: '1F1F8 1F1FB'),
    (Name: 'electric_plug'; CodePoints: '1F50C'),
    (Name: 'elephant'; CodePoints: '1F418'),
    (Name: 'elevator'; CodePoints: '1F6D7'),
    (Name: 'elf'; CodePoints: '1F9DD'),
    (Name: 'elf_man'; CodePoints: '1F9DD 200D 2642 FE0F'),
    (Name: 'elf_woman'; CodePoints: '1F9DD 200D 2640 FE0F'),
    (Name: 'email'; CodePoints: '1F4E7'),
    (Name: 'empty_nest'; CodePoints: '1FAB9'),
    (Name: 'end'; CodePoints: '1F51A'),
    (Name: 'england'; CodePoints: '1F3F4 E0067 E0062 E0065 E006E E0067 E007F'),
    (Name: 'envelope'; CodePoints: '2709 FE0F'),
    (Name: 'envelope_with_arrow'; CodePoints: '1F4E9'),
    (Name: 'equatorial_guinea'; CodePoints: '1F1EC 1F1F6'),
    (Name: 'eritrea'; CodePoints: '1F1EA 1F1F7'),
    (Name: 'es'; CodePoints: '1F1EA 1F1F8'),
    (Name: 'estonia'; CodePoints: '1F1EA 1F1EA'),
    (Name: 'ethiopia'; CodePoints: '1F1EA 1F1F9'),
    (Name: 'eu'; CodePoints: '1F1EA 1F1FA'),
    (Name: 'euro'; CodePoints: '1F4B6'),
    (Name: 'european_castle'; CodePoints: '1F3F0'),
    (Name: 'european_post_office'; CodePoints: '1F3E4'),
    (Name: 'european_union'; CodePoints: '1F1EA 1F1FA'),
    (Name: 'evergreen_tree'; CodePoints: '1F332'),
    (Name: 'exclamation'; CodePoints: '2757'),
    (Name: 'exploding_head'; CodePoints: '1F92F'),
    (Name: 'expressionless'; CodePoints: '1F611'),
    (Name: 'eye'; CodePoints: '1F441 FE0F'),
    (Name: 'eye_speech_bubble'; CodePoints: '1F441 FE0F 200D 1F5E8 FE0F'),
    (Name: 'eyeglasses'; CodePoints: '1F453'),
    (Name: 'eyes'; CodePoints: '1F440'),
    (Name: 'face_exhaling'; CodePoints: '1F62E 200D 1F4A8'),
    (Name: 'face_holding_back_tears'; CodePoints: '1F979'),
    (Name: 'face_in_clouds'; CodePoints: '1F636 200D 1F32B FE0F'),
    (Name: 'face_with_diagonal_mouth'; CodePoints: '1FAE4'),
    (Name: 'face_with_head_bandage'; CodePoints: '1F915'),
    (Name: 'face_with_open_eyes_and_hand_over_mouth'; CodePoints: '1FAE2'),
    (Name: 'face_with_peeking_eye'; CodePoints: '1FAE3'),
    (Name: 'face_with_spiral_eyes'; CodePoints: '1F635 200D 1F4AB'),
    (Name: 'face_with_thermometer'; CodePoints: '1F912'),
    (Name: 'facepalm'; CodePoints: '1F926'),
    (Name: 'facepunch'; CodePoints: '1F44A'),
    (Name: 'factory'; CodePoints: '1F3ED'),
    (Name: 'factory_worker'; CodePoints: '1F9D1 200D 1F3ED'),
    (Name: 'fairy'; CodePoints: '1F9DA'),
    (Name: 'fairy_man'; CodePoints: '1F9DA 200D 2642 FE0F'),
    (Name: 'fairy_woman'; CodePoints: '1F9DA 200D 2640 FE0F'),
    (Name: 'falafel'; CodePoints: '1F9C6'),
    (Name: 'falkland_islands'; CodePoints: '1F1EB 1F1F0'),
    (Name: 'fallen_leaf'; CodePoints: '1F342'),
    (Name: 'family'; CodePoints: '1F46A'),
    (Name: 'family_man_boy'; CodePoints: '1F468 200D 1F466'),
    (Name: 'family_man_boy_boy'; CodePoints: '1F468 200D 1F466 200D 1F466'),
    (Name: 'family_man_girl'; CodePoints: '1F468 200D 1F467'),
    (Name: 'family_man_girl_boy'; CodePoints: '1F468 200D 1F467 200D 1F466'),
    (Name: 'family_man_girl_girl'; CodePoints: '1F468 200D 1F467 200D 1F467'),
    (Name: 'family_man_man_boy'; CodePoints: '1F468 200D 1F468 200D 1F466'),
    (Name: 'family_man_man_boy_boy'; CodePoints: '1F468 200D 1F468 200D 1F466 200D 1F466'),
    (Name: 'family_man_man_girl'; CodePoints: '1F468 200D 1F468 200D 1F467'),
    (Name: 'family_man_man_girl_boy'; CodePoints: '1F468 200D 1F468 200D 1F467 200D 1F466'),
    (Name: 'family_man_man_girl_girl'; CodePoints: '1F468 200D 1F468 200D 1F467 200D 1F467'),
    (Name: 'family_man_woman_boy'; CodePoints: '1F468 200D 1F469 200D 1F466'),
    (Name: 'family_man_woman_boy_boy'; CodePoints: '1F468 200D 1F469 200D 1F466 200D 1F466'),
    (Name: 'family_man_woman_girl'; CodePoints: '1F468 200D 1F469 200D 1F467'),
    (Name: 'family_man_woman_girl_boy'; CodePoints: '1F468 200D 1F469 200D 1F467 200D 1F466'),
    (Name: 'family_man_woman_girl_girl'; CodePoints: '1F468 200D 1F469 200D 1F467 200D 1F467'),
    (Name: 'family_woman_boy'; CodePoints: '1F469 200D 1F466'),
    (Name: 'family_woman_boy_boy'; CodePoints: '1F469 200D 1F466 200D 1F466'),
    (Name: 'family_woman_girl'; CodePoints: '1F469 200D 1F467'),
    (Name: 'family_woman_girl_boy'; CodePoints: '1F469 200D 1F467 200D 1F466'),
    (Name: 'family_woman_girl_girl'; CodePoints: '1F469 200D 1F467 200D 1F467'),
    (Name: 'family_woman_woman_boy'; CodePoints: '1F469 200D 1F469 200D 1F466'),
    (Name: 'family_woman_woman_boy_boy'; CodePoints: '1F469 200D 1F469 200D 1F466 200D 1F466'),
    (Name: 'family_woman_woman_girl'; CodePoints: '1F469 200D 1F469 200D 1F467'),
    (Name: 'family_woman_woman_girl_boy'; CodePoints: '1F469 200D 1F469 200D 1F467 200D 1F466'),
    (Name: 'family_woman_woman_girl_girl'; CodePoints: '1F469 200D 1F469 200D 1F467 200D 1F467'),
    (Name: 'farmer'; CodePoints: '1F9D1 200D 1F33E'),
    (Name: 'faroe_islands'; CodePoints: '1F1EB 1F1F4'),
    (Name: 'fast_forward'; CodePoints: '23E9'),
    (Name: 'fax'; CodePoints: '1F4E0'),
    (Name: 'fearful'; CodePoints: '1F628'),
    (Name: 'feather'; CodePoints: '1FAB6'),
    (Name: 'feet'; CodePoints: '1F43E'),
    (Name: 'female_detective'; CodePoints: '1F575 FE0F 200D 2640 FE0F'),
    (Name: 'female_sign'; CodePoints: '2640 FE0F'),
    (Name: 'ferris_wheel'; CodePoints: '1F3A1'),
    (Name: 'ferry'; CodePoints: '26F4 FE0F'),
    (Name: 'field_hockey'; CodePoints: '1F3D1'),
    (Name: 'fiji'; CodePoints: '1F1EB 1F1EF'),
    (Name: 'file_cabinet'; CodePoints: '1F5C4 FE0F'),
    (Name: 'file_folder'; CodePoints: '1F4C1'),
    (Name: 'film_projector'; CodePoints: '1F4FD FE0F'),
    (Name: 'film_strip'; CodePoints: '1F39E FE0F'),
    (Name: 'finland'; CodePoints: '1F1EB 1F1EE'),
    (Name: 'fire'; CodePoints: '1F525'),
    (Name: 'fire_engine'; CodePoints: '1F692'),
    (Name: 'fire_extinguisher'; CodePoints: '1F9EF'),
    (Name: 'firecracker'; CodePoints: '1F9E8'),
    (Name: 'firefighter'; CodePoints: '1F9D1 200D 1F692'),
    (Name: 'fireworks'; CodePoints: '1F386'),
    (Name: 'first_quarter_moon'; CodePoints: '1F313'),
    (Name: 'first_quarter_moon_with_face'; CodePoints: '1F31B'),
    (Name: 'fish'; CodePoints: '1F41F'),
    (Name: 'fish_cake'; CodePoints: '1F365'),
    (Name: 'fishing_pole_and_fish'; CodePoints: '1F3A3'),
    (Name: 'fist'; CodePoints: '270A'),
    (Name: 'fist_left'; CodePoints: '1F91B'),
    (Name: 'fist_oncoming'; CodePoints: '1F44A'),
    (Name: 'fist_raised'; CodePoints: '270A'),
    (Name: 'fist_right'; CodePoints: '1F91C'),
    (Name: 'five'; CodePoints: '0035 FE0F 20E3'),
    (Name: 'flags'; CodePoints: '1F38F'),
    (Name: 'flamingo'; CodePoints: '1F9A9'),
    (Name: 'flashlight'; CodePoints: '1F526'),
    (Name: 'flat_shoe'; CodePoints: '1F97F'),
    (Name: 'flatbread'; CodePoints: '1FAD3'),
    (Name: 'fleur_de_lis'; CodePoints: '269C FE0F'),
    (Name: 'flight_arrival'; CodePoints: '1F6EC'),
    (Name: 'flight_departure'; CodePoints: '1F6EB'),
    (Name: 'flipper'; CodePoints: '1F42C'),
    (Name: 'floppy_disk'; CodePoints: '1F4BE'),
    (Name: 'flower_playing_cards'; CodePoints: '1F3B4'),
    (Name: 'flushed'; CodePoints: '1F633'),
    (Name: 'fly'; CodePoints: '1FAB0'),
    (Name: 'flying_disc'; CodePoints: '1F94F'),
    (Name: 'flying_saucer'; CodePoints: '1F6F8'),
    (Name: 'fog'; CodePoints: '1F32B FE0F'),
    (Name: 'foggy'; CodePoints: '1F301'),
    (Name: 'fondue'; CodePoints: '1FAD5'),
    (Name: 'foot'; CodePoints: '1F9B6'),
    (Name: 'football'; CodePoints: '1F3C8'),
    (Name: 'footprints'; CodePoints: '1F463'),
    (Name: 'fork_and_knife'; CodePoints: '1F374'),
    (Name: 'fortune_cookie'; CodePoints: '1F960'),
    (Name: 'fountain'; CodePoints: '26F2'),
    (Name: 'fountain_pen'; CodePoints: '1F58B FE0F'),
    (Name: 'four'; CodePoints: '0034 FE0F 20E3'),
    (Name: 'four_leaf_clover'; CodePoints: '1F340'),
    (Name: 'fox_face'; CodePoints: '1F98A'),
    (Name: 'fr'; CodePoints: '1F1EB 1F1F7'),
    (Name: 'framed_picture'; CodePoints: '1F5BC FE0F'),
    (Name: 'free'; CodePoints: '1F193'),
    (Name: 'french_guiana'; CodePoints: '1F1EC 1F1EB'),
    (Name: 'french_polynesia'; CodePoints: '1F1F5 1F1EB'),
    (Name: 'french_southern_territories'; CodePoints: '1F1F9 1F1EB'),
    (Name: 'fried_egg'; CodePoints: '1F373'),
    (Name: 'fried_shrimp'; CodePoints: '1F364'),
    (Name: 'fries'; CodePoints: '1F35F'),
    (Name: 'frog'; CodePoints: '1F438'),
    (Name: 'frowning'; CodePoints: '1F626'),
    (Name: 'frowning_face'; CodePoints: '2639 FE0F'),
    (Name: 'frowning_man'; CodePoints: '1F64D 200D 2642 FE0F'),
    (Name: 'frowning_person'; CodePoints: '1F64D'),
    (Name: 'frowning_woman'; CodePoints: '1F64D 200D 2640 FE0F'),
    (Name: 'fu'; CodePoints: '1F595'),
    (Name: 'fuelpump'; CodePoints: '26FD'),
    (Name: 'full_moon'; CodePoints: '1F315'),
    (Name: 'full_moon_with_face'; CodePoints: '1F31D'),
    (Name: 'funeral_urn'; CodePoints: '26B1 FE0F'),
    (Name: 'gabon'; CodePoints: '1F1EC 1F1E6'),
    (Name: 'gambia'; CodePoints: '1F1EC 1F1F2'),
    (Name: 'game_die'; CodePoints: '1F3B2'),
    (Name: 'garlic'; CodePoints: '1F9C4'),
    (Name: 'gb'; CodePoints: '1F1EC 1F1E7'),
    (Name: 'gear'; CodePoints: '2699 FE0F'),
    (Name: 'gem'; CodePoints: '1F48E'),
    (Name: 'gemini'; CodePoints: '264A'),
    (Name: 'genie'; CodePoints: '1F9DE'),
    (Name: 'genie_man'; CodePoints: '1F9DE 200D 2642 FE0F'),
    (Name: 'genie_woman'; CodePoints: '1F9DE 200D 2640 FE0F'),
    (Name: 'georgia'; CodePoints: '1F1EC 1F1EA'),
    (Name: 'ghana'; CodePoints: '1F1EC 1F1ED'),
    (Name: 'ghost'; CodePoints: '1F47B'),
    (Name: 'gibraltar'; CodePoints: '1F1EC 1F1EE'),
    (Name: 'gift'; CodePoints: '1F381'),
    (Name: 'gift_heart'; CodePoints: '1F49D'),
    (Name: 'giraffe'; CodePoints: '1F992'),
    (Name: 'girl'; CodePoints: '1F467'),
    (Name: 'globe_with_meridians'; CodePoints: '1F310'),
    (Name: 'gloves'; CodePoints: '1F9E4'),
    (Name: 'goal_net'; CodePoints: '1F945'),
    (Name: 'goat'; CodePoints: '1F410'),
    (Name: 'goggles'; CodePoints: '1F97D'),
    (Name: 'golf'; CodePoints: '26F3'),
    (Name: 'golfing'; CodePoints: '1F3CC FE0F'),
    (Name: 'golfing_man'; CodePoints: '1F3CC FE0F 200D 2642 FE0F'),
    (Name: 'golfing_woman'; CodePoints: '1F3CC FE0F 200D 2640 FE0F'),
    (Name: 'gorilla'; CodePoints: '1F98D'),
    (Name: 'grapes'; CodePoints: '1F347'),
    (Name: 'greece'; CodePoints: '1F1EC 1F1F7'),
    (Name: 'green_apple'; CodePoints: '1F34F'),
    (Name: 'green_book'; CodePoints: '1F4D7'),
    (Name: 'green_circle'; CodePoints: '1F7E2'),
    (Name: 'green_heart'; CodePoints: '1F49A'),
    (Name: 'green_salad'; CodePoints: '1F957'),
    (Name: 'green_square'; CodePoints: '1F7E9'),
    (Name: 'greenland'; CodePoints: '1F1EC 1F1F1'),
    (Name: 'grenada'; CodePoints: '1F1EC 1F1E9'),
    (Name: 'grey_exclamation'; CodePoints: '2755'),
    (Name: 'grey_question'; CodePoints: '2754'),
    (Name: 'grimacing'; CodePoints: '1F62C'),
    (Name: 'grin'; CodePoints: '1F601'),
    (Name: 'grinning'; CodePoints: '1F600'),
    (Name: 'guadeloupe'; CodePoints: '1F1EC 1F1F5'),
    (Name: 'guam'; CodePoints: '1F1EC 1F1FA'),
    (Name: 'guard'; CodePoints: '1F482'),
    (Name: 'guardsman'; CodePoints: '1F482 200D 2642 FE0F'),
    (Name: 'guardswoman'; CodePoints: '1F482 200D 2640 FE0F'),
    (Name: 'guatemala'; CodePoints: '1F1EC 1F1F9'),
    (Name: 'guernsey'; CodePoints: '1F1EC 1F1EC'),
    (Name: 'guide_dog'; CodePoints: '1F9AE'),
    (Name: 'guinea'; CodePoints: '1F1EC 1F1F3'),
    (Name: 'guinea_bissau'; CodePoints: '1F1EC 1F1FC'),
    (Name: 'guitar'; CodePoints: '1F3B8'),
    (Name: 'gun'; CodePoints: '1F52B'),
    (Name: 'guyana'; CodePoints: '1F1EC 1F1FE'),
    (Name: 'haircut'; CodePoints: '1F487'),
    (Name: 'haircut_man'; CodePoints: '1F487 200D 2642 FE0F'),
    (Name: 'haircut_woman'; CodePoints: '1F487 200D 2640 FE0F'),
    (Name: 'haiti'; CodePoints: '1F1ED 1F1F9'),
    (Name: 'hamburger'; CodePoints: '1F354'),
    (Name: 'hammer'; CodePoints: '1F528'),
    (Name: 'hammer_and_pick'; CodePoints: '2692 FE0F'),
    (Name: 'hammer_and_wrench'; CodePoints: '1F6E0 FE0F'),
    (Name: 'hamsa'; CodePoints: '1FAAC'),
    (Name: 'hamster'; CodePoints: '1F439'),
    (Name: 'hand'; CodePoints: '270B'),
    (Name: 'hand_over_mouth'; CodePoints: '1F92D'),
    (Name: 'hand_with_index_finger_and_thumb_crossed'; CodePoints: '1FAF0'),
    (Name: 'handbag'; CodePoints: '1F45C'),
    (Name: 'handball_person'; CodePoints: '1F93E'),
    (Name: 'handshake'; CodePoints: '1F91D'),
    (Name: 'hankey'; CodePoints: '1F4A9'),
    (Name: 'hash'; CodePoints: '0023 FE0F 20E3'),
    (Name: 'hatched_chick'; CodePoints: '1F425'),
    (Name: 'hatching_chick'; CodePoints: '1F423'),
    (Name: 'headphones'; CodePoints: '1F3A7'),
    (Name: 'headstone'; CodePoints: '1FAA6'),
    (Name: 'health_worker'; CodePoints: '1F9D1 200D 2695 FE0F'),
    (Name: 'hear_no_evil'; CodePoints: '1F649'),
    (Name: 'heard_mcdonald_islands'; CodePoints: '1F1ED 1F1F2'),
    (Name: 'heart'; CodePoints: '2764 FE0F'),
    (Name: 'heart_decoration'; CodePoints: '1F49F'),
    (Name: 'heart_eyes'; CodePoints: '1F60D'),
    (Name: 'heart_eyes_cat'; CodePoints: '1F63B'),
    (Name: 'heart_hands'; CodePoints: '1FAF6'),
    (Name: 'heart_on_fire'; CodePoints: '2764 FE0F 200D 1F525'),
    (Name: 'heartbeat'; CodePoints: '1F493'),
    (Name: 'heartpulse'; CodePoints: '1F497'),
    (Name: 'hearts'; CodePoints: '2665 FE0F'),
    (Name: 'heavy_check_mark'; CodePoints: '2714 FE0F'),
    (Name: 'heavy_division_sign'; CodePoints: '2797'),
    (Name: 'heavy_dollar_sign'; CodePoints: '1F4B2'),
    (Name: 'heavy_equals_sign'; CodePoints: '1F7F0'),
    (Name: 'heavy_exclamation_mark'; CodePoints: '2757'),
    (Name: 'heavy_heart_exclamation'; CodePoints: '2763 FE0F'),
    (Name: 'heavy_minus_sign'; CodePoints: '2796'),
    (Name: 'heavy_multiplication_x'; CodePoints: '2716 FE0F'),
    (Name: 'heavy_plus_sign'; CodePoints: '2795'),
    (Name: 'hedgehog'; CodePoints: '1F994'),
    (Name: 'helicopter'; CodePoints: '1F681'),
    (Name: 'herb'; CodePoints: '1F33F'),
    (Name: 'hibiscus'; CodePoints: '1F33A'),
    (Name: 'high_brightness'; CodePoints: '1F506'),
    (Name: 'high_heel'; CodePoints: '1F460'),
    (Name: 'hiking_boot'; CodePoints: '1F97E'),
    (Name: 'hindu_temple'; CodePoints: '1F6D5'),
    (Name: 'hippopotamus'; CodePoints: '1F99B'),
    (Name: 'hocho'; CodePoints: '1F52A'),
    (Name: 'hole'; CodePoints: '1F573 FE0F'),
    (Name: 'honduras'; CodePoints: '1F1ED 1F1F3'),
    (Name: 'honey_pot'; CodePoints: '1F36F'),
    (Name: 'honeybee'; CodePoints: '1F41D'),
    (Name: 'hong_kong'; CodePoints: '1F1ED 1F1F0'),
    (Name: 'hook'; CodePoints: '1FA9D'),
    (Name: 'horse'; CodePoints: '1F434'),
    (Name: 'horse_racing'; CodePoints: '1F3C7'),
    (Name: 'hospital'; CodePoints: '1F3E5'),
    (Name: 'hot_face'; CodePoints: '1F975'),
    (Name: 'hot_pepper'; CodePoints: '1F336 FE0F'),
    (Name: 'hotdog'; CodePoints: '1F32D'),
    (Name: 'hotel'; CodePoints: '1F3E8'),
    (Name: 'hotsprings'; CodePoints: '2668 FE0F'),
    (Name: 'hourglass'; CodePoints: '231B'),
    (Name: 'hourglass_flowing_sand'; CodePoints: '23F3'),
    (Name: 'house'; CodePoints: '1F3E0'),
    (Name: 'house_with_garden'; CodePoints: '1F3E1'),
    (Name: 'houses'; CodePoints: '1F3D8 FE0F'),
    (Name: 'hugs'; CodePoints: '1F917'),
    (Name: 'hungary'; CodePoints: '1F1ED 1F1FA'),
    (Name: 'hushed'; CodePoints: '1F62F'),
    (Name: 'hut'; CodePoints: '1F6D6'),
    (Name: 'ice_cream'; CodePoints: '1F368'),
    (Name: 'ice_cube'; CodePoints: '1F9CA'),
    (Name: 'ice_hockey'; CodePoints: '1F3D2'),
    (Name: 'ice_skate'; CodePoints: '26F8 FE0F'),
    (Name: 'icecream'; CodePoints: '1F366'),
    (Name: 'iceland'; CodePoints: '1F1EE 1F1F8'),
    (Name: 'id'; CodePoints: '1F194'),
    (Name: 'identification_card'; CodePoints: '1FAAA'),
    (Name: 'ideograph_advantage'; CodePoints: '1F250'),
    (Name: 'imp'; CodePoints: '1F47F'),
    (Name: 'inbox_tray'; CodePoints: '1F4E5'),
    (Name: 'incoming_envelope'; CodePoints: '1F4E8'),
    (Name: 'index_pointing_at_the_viewer'; CodePoints: '1FAF5'),
    (Name: 'india'; CodePoints: '1F1EE 1F1F3'),
    (Name: 'indonesia'; CodePoints: '1F1EE 1F1E9'),
    (Name: 'infinity'; CodePoints: '267E FE0F'),
    (Name: 'information_desk_person'; CodePoints: '1F481'),
    (Name: 'information_source'; CodePoints: '2139 FE0F'),
    (Name: 'innocent'; CodePoints: '1F607'),
    (Name: 'interrobang'; CodePoints: '2049 FE0F'),
    (Name: 'iphone'; CodePoints: '1F4F1'),
    (Name: 'iran'; CodePoints: '1F1EE 1F1F7'),
    (Name: 'iraq'; CodePoints: '1F1EE 1F1F6'),
    (Name: 'ireland'; CodePoints: '1F1EE 1F1EA'),
    (Name: 'isle_of_man'; CodePoints: '1F1EE 1F1F2'),
    (Name: 'israel'; CodePoints: '1F1EE 1F1F1'),
    (Name: 'it'; CodePoints: '1F1EE 1F1F9'),
    (Name: 'izakaya_lantern'; CodePoints: '1F3EE'),
    (Name: 'jack_o_lantern'; CodePoints: '1F383'),
    (Name: 'jamaica'; CodePoints: '1F1EF 1F1F2'),
    (Name: 'japan'; CodePoints: '1F5FE'),
    (Name: 'japanese_castle'; CodePoints: '1F3EF'),
    (Name: 'japanese_goblin'; CodePoints: '1F47A'),
    (Name: 'japanese_ogre'; CodePoints: '1F479'),
    (Name: 'jar'; CodePoints: '1FAD9'),
    (Name: 'jeans'; CodePoints: '1F456'),
    (Name: 'jersey'; CodePoints: '1F1EF 1F1EA'),
    (Name: 'jigsaw'; CodePoints: '1F9E9'),
    (Name: 'jordan'; CodePoints: '1F1EF 1F1F4'),
    (Name: 'joy'; CodePoints: '1F602'),
    (Name: 'joy_cat'; CodePoints: '1F639'),
    (Name: 'joystick'; CodePoints: '1F579 FE0F'),
    (Name: 'jp'; CodePoints: '1F1EF 1F1F5'),
    (Name: 'judge'; CodePoints: '1F9D1 200D 2696 FE0F'),
    (Name: 'juggling_person'; CodePoints: '1F939'),
    (Name: 'kaaba'; CodePoints: '1F54B'),
    (Name: 'kangaroo'; CodePoints: '1F998'),
    (Name: 'kazakhstan'; CodePoints: '1F1F0 1F1FF'),
    (Name: 'kenya'; CodePoints: '1F1F0 1F1EA'),
    (Name: 'key'; CodePoints: '1F511'),
    (Name: 'keyboard'; CodePoints: '2328 FE0F'),
    (Name: 'keycap_ten'; CodePoints: '1F51F'),
    (Name: 'kick_scooter'; CodePoints: '1F6F4'),
    (Name: 'kimono'; CodePoints: '1F458'),
    (Name: 'kiribati'; CodePoints: '1F1F0 1F1EE'),
    (Name: 'kiss'; CodePoints: '1F48B'),
    (Name: 'kissing'; CodePoints: '1F617'),
    (Name: 'kissing_cat'; CodePoints: '1F63D'),
    (Name: 'kissing_closed_eyes'; CodePoints: '1F61A'),
    (Name: 'kissing_heart'; CodePoints: '1F618'),
    (Name: 'kissing_smiling_eyes'; CodePoints: '1F619'),
    (Name: 'kite'; CodePoints: '1FA81'),
    (Name: 'kiwi_fruit'; CodePoints: '1F95D'),
    (Name: 'kneeling_man'; CodePoints: '1F9CE 200D 2642 FE0F'),
    (Name: 'kneeling_person'; CodePoints: '1F9CE'),
    (Name: 'kneeling_woman'; CodePoints: '1F9CE 200D 2640 FE0F'),
    (Name: 'knife'; CodePoints: '1F52A'),
    (Name: 'knot'; CodePoints: '1FAA2'),
    (Name: 'koala'; CodePoints: '1F428'),
    (Name: 'koko'; CodePoints: '1F201'),
    (Name: 'kosovo'; CodePoints: '1F1FD 1F1F0'),
    (Name: 'kr'; CodePoints: '1F1F0 1F1F7'),
    (Name: 'kuwait'; CodePoints: '1F1F0 1F1FC'),
    (Name: 'kyrgyzstan'; CodePoints: '1F1F0 1F1EC'),
    (Name: 'lab_coat'; CodePoints: '1F97C'),
    (Name: 'label'; CodePoints: '1F3F7 FE0F'),
    (Name: 'lacrosse'; CodePoints: '1F94D'),
    (Name: 'ladder'; CodePoints: '1FA9C'),
    (Name: 'lady_beetle'; CodePoints: '1F41E'),
    (Name: 'lantern'; CodePoints: '1F3EE'),
    (Name: 'laos'; CodePoints: '1F1F1 1F1E6'),
    (Name: 'large_blue_circle'; CodePoints: '1F535'),
    (Name: 'large_blue_diamond'; CodePoints: '1F537'),
    (Name: 'large_orange_diamond'; CodePoints: '1F536'),
    (Name: 'last_quarter_moon'; CodePoints: '1F317'),
    (Name: 'last_quarter_moon_with_face'; CodePoints: '1F31C'),
    (Name: 'latin_cross'; CodePoints: '271D FE0F'),
    (Name: 'latvia'; CodePoints: '1F1F1 1F1FB'),
    (Name: 'laughing'; CodePoints: '1F606'),
    (Name: 'leafy_green'; CodePoints: '1F96C'),
    (Name: 'leaves'; CodePoints: '1F343'),
    (Name: 'lebanon'; CodePoints: '1F1F1 1F1E7'),
    (Name: 'ledger'; CodePoints: '1F4D2'),
    (Name: 'left_luggage'; CodePoints: '1F6C5'),
    (Name: 'left_right_arrow'; CodePoints: '2194 FE0F'),
    (Name: 'left_speech_bubble'; CodePoints: '1F5E8 FE0F'),
    (Name: 'leftwards_arrow_with_hook'; CodePoints: '21A9 FE0F'),
    (Name: 'leftwards_hand'; CodePoints: '1FAF2'),
    (Name: 'leg'; CodePoints: '1F9B5'),
    (Name: 'lemon'; CodePoints: '1F34B'),
    (Name: 'leo'; CodePoints: '264C'),
    (Name: 'leopard'; CodePoints: '1F406'),
    (Name: 'lesotho'; CodePoints: '1F1F1 1F1F8'),
    (Name: 'level_slider'; CodePoints: '1F39A FE0F'),
    (Name: 'liberia'; CodePoints: '1F1F1 1F1F7'),
    (Name: 'libra'; CodePoints: '264E'),
    (Name: 'libya'; CodePoints: '1F1F1 1F1FE'),
    (Name: 'liechtenstein'; CodePoints: '1F1F1 1F1EE'),
    (Name: 'light_rail'; CodePoints: '1F688'),
    (Name: 'link'; CodePoints: '1F517'),
    (Name: 'lion'; CodePoints: '1F981'),
    (Name: 'lips'; CodePoints: '1F444'),
    (Name: 'lipstick'; CodePoints: '1F484'),
    (Name: 'lithuania'; CodePoints: '1F1F1 1F1F9'),
    (Name: 'lizard'; CodePoints: '1F98E'),
    (Name: 'llama'; CodePoints: '1F999'),
    (Name: 'lobster'; CodePoints: '1F99E'),
    (Name: 'lock'; CodePoints: '1F512'),
    (Name: 'lock_with_ink_pen'; CodePoints: '1F50F'),
    (Name: 'lollipop'; CodePoints: '1F36D'),
    (Name: 'long_drum'; CodePoints: '1FA98'),
    (Name: 'loop'; CodePoints: '27BF'),
    (Name: 'lotion_bottle'; CodePoints: '1F9F4'),
    (Name: 'lotus'; CodePoints: '1FAB7'),
    (Name: 'lotus_position'; CodePoints: '1F9D8'),
    (Name: 'lotus_position_man'; CodePoints: '1F9D8 200D 2642 FE0F'),
    (Name: 'lotus_position_woman'; CodePoints: '1F9D8 200D 2640 FE0F'),
    (Name: 'loud_sound'; CodePoints: '1F50A'),
    (Name: 'loudspeaker'; CodePoints: '1F4E2'),
    (Name: 'love_hotel'; CodePoints: '1F3E9'),
    (Name: 'love_letter'; CodePoints: '1F48C'),
    (Name: 'love_you_gesture'; CodePoints: '1F91F'),
    (Name: 'low_battery'; CodePoints: '1FAAB'),
    (Name: 'low_brightness'; CodePoints: '1F505'),
    (Name: 'luggage'; CodePoints: '1F9F3'),
    (Name: 'lungs'; CodePoints: '1FAC1'),
    (Name: 'luxembourg'; CodePoints: '1F1F1 1F1FA'),
    (Name: 'lying_face'; CodePoints: '1F925'),
    (Name: 'm'; CodePoints: '24C2 FE0F'),
    (Name: 'macau'; CodePoints: '1F1F2 1F1F4'),
    (Name: 'macedonia'; CodePoints: '1F1F2 1F1F0'),
    (Name: 'madagascar'; CodePoints: '1F1F2 1F1EC'),
    (Name: 'mag'; CodePoints: '1F50D'),
    (Name: 'mag_right'; CodePoints: '1F50E'),
    (Name: 'mage'; CodePoints: '1F9D9'),
    (Name: 'mage_man'; CodePoints: '1F9D9 200D 2642 FE0F'),
    (Name: 'mage_woman'; CodePoints: '1F9D9 200D 2640 FE0F'),
    (Name: 'magic_wand'; CodePoints: '1FA84'),
    (Name: 'magnet'; CodePoints: '1F9F2'),
    (Name: 'mahjong'; CodePoints: '1F004'),
    (Name: 'mailbox'; CodePoints: '1F4EB'),
    (Name: 'mailbox_closed'; CodePoints: '1F4EA'),
    (Name: 'mailbox_with_mail'; CodePoints: '1F4EC'),
    (Name: 'mailbox_with_no_mail'; CodePoints: '1F4ED'),
    (Name: 'malawi'; CodePoints: '1F1F2 1F1FC'),
    (Name: 'malaysia'; CodePoints: '1F1F2 1F1FE'),
    (Name: 'maldives'; CodePoints: '1F1F2 1F1FB'),
    (Name: 'male_detective'; CodePoints: '1F575 FE0F 200D 2642 FE0F'),
    (Name: 'male_sign'; CodePoints: '2642 FE0F'),
    (Name: 'mali'; CodePoints: '1F1F2 1F1F1'),
    (Name: 'malta'; CodePoints: '1F1F2 1F1F9'),
    (Name: 'mammoth'; CodePoints: '1F9A3'),
    (Name: 'man'; CodePoints: '1F468'),
    (Name: 'man_artist'; CodePoints: '1F468 200D 1F3A8'),
    (Name: 'man_astronaut'; CodePoints: '1F468 200D 1F680'),
    (Name: 'man_beard'; CodePoints: '1F9D4 200D 2642 FE0F'),
    (Name: 'man_cartwheeling'; CodePoints: '1F938 200D 2642 FE0F'),
    (Name: 'man_cook'; CodePoints: '1F468 200D 1F373'),
    (Name: 'man_dancing'; CodePoints: '1F57A'),
    (Name: 'man_facepalming'; CodePoints: '1F926 200D 2642 FE0F'),
    (Name: 'man_factory_worker'; CodePoints: '1F468 200D 1F3ED'),
    (Name: 'man_farmer'; CodePoints: '1F468 200D 1F33E'),
    (Name: 'man_feeding_baby'; CodePoints: '1F468 200D 1F37C'),
    (Name: 'man_firefighter'; CodePoints: '1F468 200D 1F692'),
    (Name: 'man_health_worker'; CodePoints: '1F468 200D 2695 FE0F'),
    (Name: 'man_in_manual_wheelchair'; CodePoints: '1F468 200D 1F9BD'),
    (Name: 'man_in_motorized_wheelchair'; CodePoints: '1F468 200D 1F9BC'),
    (Name: 'man_in_tuxedo'; CodePoints: '1F935 200D 2642 FE0F'),
    (Name: 'man_judge'; CodePoints: '1F468 200D 2696 FE0F'),
    (Name: 'man_juggling'; CodePoints: '1F939 200D 2642 FE0F'),
    (Name: 'man_mechanic'; CodePoints: '1F468 200D 1F527'),
    (Name: 'man_office_worker'; CodePoints: '1F468 200D 1F4BC'),
    (Name: 'man_pilot'; CodePoints: '1F468 200D 2708 FE0F'),
    (Name: 'man_playing_handball'; CodePoints: '1F93E 200D 2642 FE0F'),
    (Name: 'man_playing_water_polo'; CodePoints: '1F93D 200D 2642 FE0F'),
    (Name: 'man_scientist'; CodePoints: '1F468 200D 1F52C'),
    (Name: 'man_shrugging'; CodePoints: '1F937 200D 2642 FE0F'),
    (Name: 'man_singer'; CodePoints: '1F468 200D 1F3A4'),
    (Name: 'man_student'; CodePoints: '1F468 200D 1F393'),
    (Name: 'man_teacher'; CodePoints: '1F468 200D 1F3EB'),
    (Name: 'man_technologist'; CodePoints: '1F468 200D 1F4BB'),
    (Name: 'man_with_gua_pi_mao'; CodePoints: '1F472'),
    (Name: 'man_with_probing_cane'; CodePoints: '1F468 200D 1F9AF'),
    (Name: 'man_with_turban'; CodePoints: '1F473 200D 2642 FE0F'),
    (Name: 'man_with_veil'; CodePoints: '1F470 200D 2642 FE0F'),
    (Name: 'mandarin'; CodePoints: '1F34A'),
    (Name: 'mango'; CodePoints: '1F96D'),
    (Name: 'mans_shoe'; CodePoints: '1F45E'),
    (Name: 'mantelpiece_clock'; CodePoints: '1F570 FE0F'),
    (Name: 'manual_wheelchair'; CodePoints: '1F9BD'),
    (Name: 'maple_leaf'; CodePoints: '1F341'),
    (Name: 'marshall_islands'; CodePoints: '1F1F2 1F1ED'),
    (Name: 'martial_arts_uniform'; CodePoints: '1F94B'),
    (Name: 'martinique'; CodePoints: '1F1F2 1F1F6'),
    (Name: 'mask'; CodePoints: '1F637'),
    (Name: 'massage'; CodePoints: '1F486'),
    (Name: 'massage_man'; CodePoints: '1F486 200D 2642 FE0F'),
    (Name: 'massage_woman'; CodePoints: '1F486 200D 2640 FE0F'),
    (Name: 'mate'; CodePoints: '1F9C9'),
    (Name: 'mauritania'; CodePoints: '1F1F2 1F1F7'),
    (Name: 'mauritius'; CodePoints: '1F1F2 1F1FA'),
    (Name: 'mayotte'; CodePoints: '1F1FE 1F1F9'),
    (Name: 'meat_on_bone'; CodePoints: '1F356'),
    (Name: 'mechanic'; CodePoints: '1F9D1 200D 1F527'),
    (Name: 'mechanical_arm'; CodePoints: '1F9BE'),
    (Name: 'mechanical_leg'; CodePoints: '1F9BF'),
    (Name: 'medal_military'; CodePoints: '1F396 FE0F'),
    (Name: 'medal_sports'; CodePoints: '1F3C5'),
    (Name: 'medical_symbol'; CodePoints: '2695 FE0F'),
    (Name: 'mega'; CodePoints: '1F4E3'),
    (Name: 'melon'; CodePoints: '1F348'),
    (Name: 'melting_face'; CodePoints: '1FAE0'),
    (Name: 'memo'; CodePoints: '1F4DD'),
    (Name: 'men_wrestling'; CodePoints: '1F93C 200D 2642 FE0F'),
    (Name: 'mending_heart'; CodePoints: '2764 FE0F 200D 1FA79'),
    (Name: 'menorah'; CodePoints: '1F54E'),
    (Name: 'mens'; CodePoints: '1F6B9'),
    (Name: 'mermaid'; CodePoints: '1F9DC 200D 2640 FE0F'),
    (Name: 'merman'; CodePoints: '1F9DC 200D 2642 FE0F'),
    (Name: 'merperson'; CodePoints: '1F9DC'),
    (Name: 'metal'; CodePoints: '1F918'),
    (Name: 'metro'; CodePoints: '1F687'),
    (Name: 'mexico'; CodePoints: '1F1F2 1F1FD'),
    (Name: 'microbe'; CodePoints: '1F9A0'),
    (Name: 'micronesia'; CodePoints: '1F1EB 1F1F2'),
    (Name: 'microphone'; CodePoints: '1F3A4'),
    (Name: 'microscope'; CodePoints: '1F52C'),
    (Name: 'middle_finger'; CodePoints: '1F595'),
    (Name: 'military_helmet'; CodePoints: '1FA96'),
    (Name: 'milk_glass'; CodePoints: '1F95B'),
    (Name: 'milky_way'; CodePoints: '1F30C'),
    (Name: 'minibus'; CodePoints: '1F690'),
    (Name: 'minidisc'; CodePoints: '1F4BD'),
    (Name: 'mirror'; CodePoints: '1FA9E'),
    (Name: 'mirror_ball'; CodePoints: '1FAA9'),
    (Name: 'mobile_phone_off'; CodePoints: '1F4F4'),
    (Name: 'moldova'; CodePoints: '1F1F2 1F1E9'),
    (Name: 'monaco'; CodePoints: '1F1F2 1F1E8'),
    (Name: 'money_mouth_face'; CodePoints: '1F911'),
    (Name: 'money_with_wings'; CodePoints: '1F4B8'),
    (Name: 'moneybag'; CodePoints: '1F4B0'),
    (Name: 'mongolia'; CodePoints: '1F1F2 1F1F3'),
    (Name: 'monkey'; CodePoints: '1F412'),
    (Name: 'monkey_face'; CodePoints: '1F435'),
    (Name: 'monocle_face'; CodePoints: '1F9D0'),
    (Name: 'monorail'; CodePoints: '1F69D'),
    (Name: 'montenegro'; CodePoints: '1F1F2 1F1EA'),
    (Name: 'montserrat'; CodePoints: '1F1F2 1F1F8'),
    (Name: 'moon'; CodePoints: '1F314'),
    (Name: 'moon_cake'; CodePoints: '1F96E'),
    (Name: 'morocco'; CodePoints: '1F1F2 1F1E6'),
    (Name: 'mortar_board'; CodePoints: '1F393'),
    (Name: 'mosque'; CodePoints: '1F54C'),
    (Name: 'mosquito'; CodePoints: '1F99F'),
    (Name: 'motor_boat'; CodePoints: '1F6E5 FE0F'),
    (Name: 'motor_scooter'; CodePoints: '1F6F5'),
    (Name: 'motorcycle'; CodePoints: '1F3CD FE0F'),
    (Name: 'motorized_wheelchair'; CodePoints: '1F9BC'),
    (Name: 'motorway'; CodePoints: '1F6E3 FE0F'),
    (Name: 'mount_fuji'; CodePoints: '1F5FB'),
    (Name: 'mountain'; CodePoints: '26F0 FE0F'),
    (Name: 'mountain_bicyclist'; CodePoints: '1F6B5'),
    (Name: 'mountain_biking_man'; CodePoints: '1F6B5 200D 2642 FE0F'),
    (Name: 'mountain_biking_woman'; CodePoints: '1F6B5 200D 2640 FE0F'),
    (Name: 'mountain_cableway'; CodePoints: '1F6A0'),
    (Name: 'mountain_railway'; CodePoints: '1F69E'),
    (Name: 'mountain_snow'; CodePoints: '1F3D4 FE0F'),
    (Name: 'mouse'; CodePoints: '1F42D'),
    (Name: 'mouse2'; CodePoints: '1F401'),
    (Name: 'mouse_trap'; CodePoints: '1FAA4'),
    (Name: 'movie_camera'; CodePoints: '1F3A5'),
    (Name: 'moyai'; CodePoints: '1F5FF'),
    (Name: 'mozambique'; CodePoints: '1F1F2 1F1FF'),
    (Name: 'mrs_claus'; CodePoints: '1F936'),
    (Name: 'muscle'; CodePoints: '1F4AA'),
    (Name: 'mushroom'; CodePoints: '1F344'),
    (Name: 'musical_keyboard'; CodePoints: '1F3B9'),
    (Name: 'musical_note'; CodePoints: '1F3B5'),
    (Name: 'musical_score'; CodePoints: '1F3BC'),
    (Name: 'mute'; CodePoints: '1F507'),
    (Name: 'mx_claus'; CodePoints: '1F9D1 200D 1F384'),
    (Name: 'myanmar'; CodePoints: '1F1F2 1F1F2'),
    (Name: 'nail_care'; CodePoints: '1F485'),
    (Name: 'name_badge'; CodePoints: '1F4DB'),
    (Name: 'namibia'; CodePoints: '1F1F3 1F1E6'),
    (Name: 'national_park'; CodePoints: '1F3DE FE0F'),
    (Name: 'nauru'; CodePoints: '1F1F3 1F1F7'),
    (Name: 'nauseated_face'; CodePoints: '1F922'),
    (Name: 'nazar_amulet'; CodePoints: '1F9FF'),
    (Name: 'necktie'; CodePoints: '1F454'),
    (Name: 'negative_squared_cross_mark'; CodePoints: '274E'),
    (Name: 'nepal'; CodePoints: '1F1F3 1F1F5'),
    (Name: 'nerd_face'; CodePoints: '1F913'),
    (Name: 'nest_with_eggs'; CodePoints: '1FABA'),
    (Name: 'nesting_dolls'; CodePoints: '1FA86'),
    (Name: 'netherlands'; CodePoints: '1F1F3 1F1F1'),
    (Name: 'neutral_face'; CodePoints: '1F610'),
    (Name: 'new'; CodePoints: '1F195'),
    (Name: 'new_caledonia'; CodePoints: '1F1F3 1F1E8'),
    (Name: 'new_moon'; CodePoints: '1F311'),
    (Name: 'new_moon_with_face'; CodePoints: '1F31A'),
    (Name: 'new_zealand'; CodePoints: '1F1F3 1F1FF'),
    (Name: 'newspaper'; CodePoints: '1F4F0'),
    (Name: 'newspaper_roll'; CodePoints: '1F5DE FE0F'),
    (Name: 'next_track_button'; CodePoints: '23ED FE0F'),
    (Name: 'ng'; CodePoints: '1F196'),
    (Name: 'ng_man'; CodePoints: '1F645 200D 2642 FE0F'),
    (Name: 'ng_woman'; CodePoints: '1F645 200D 2640 FE0F'),
    (Name: 'nicaragua'; CodePoints: '1F1F3 1F1EE'),
    (Name: 'niger'; CodePoints: '1F1F3 1F1EA'),
    (Name: 'nigeria'; CodePoints: '1F1F3 1F1EC'),
    (Name: 'night_with_stars'; CodePoints: '1F303'),
    (Name: 'nine'; CodePoints: '0039 FE0F 20E3'),
    (Name: 'ninja'; CodePoints: '1F977'),
    (Name: 'niue'; CodePoints: '1F1F3 1F1FA'),
    (Name: 'no_bell'; CodePoints: '1F515'),
    (Name: 'no_bicycles'; CodePoints: '1F6B3'),
    (Name: 'no_entry'; CodePoints: '26D4'),
    (Name: 'no_entry_sign'; CodePoints: '1F6AB'),
    (Name: 'no_good'; CodePoints: '1F645'),
    (Name: 'no_good_man'; CodePoints: '1F645 200D 2642 FE0F'),
    (Name: 'no_good_woman'; CodePoints: '1F645 200D 2640 FE0F'),
    (Name: 'no_mobile_phones'; CodePoints: '1F4F5'),
    (Name: 'no_mouth'; CodePoints: '1F636'),
    (Name: 'no_pedestrians'; CodePoints: '1F6B7'),
    (Name: 'no_smoking'; CodePoints: '1F6AD'),
    (Name: 'non-potable_water'; CodePoints: '1F6B1'),
    (Name: 'norfolk_island'; CodePoints: '1F1F3 1F1EB'),
    (Name: 'north_korea'; CodePoints: '1F1F0 1F1F5'),
    (Name: 'northern_mariana_islands'; CodePoints: '1F1F2 1F1F5'),
    (Name: 'norway'; CodePoints: '1F1F3 1F1F4'),
    (Name: 'nose'; CodePoints: '1F443'),
    (Name: 'notebook'; CodePoints: '1F4D3'),
    (Name: 'notebook_with_decorative_cover'; CodePoints: '1F4D4'),
    (Name: 'notes'; CodePoints: '1F3B6'),
    (Name: 'nut_and_bolt'; CodePoints: '1F529'),
    (Name: 'o'; CodePoints: '2B55'),
    (Name: 'o2'; CodePoints: '1F17E FE0F'),
    (Name: 'ocean'; CodePoints: '1F30A'),
    (Name: 'octopus'; CodePoints: '1F419'),
    (Name: 'oden'; CodePoints: '1F362'),
    (Name: 'office'; CodePoints: '1F3E2'),
    (Name: 'office_worker'; CodePoints: '1F9D1 200D 1F4BC'),
    (Name: 'oil_drum'; CodePoints: '1F6E2 FE0F'),
    (Name: 'ok'; CodePoints: '1F197'),
    (Name: 'ok_hand'; CodePoints: '1F44C'),
    (Name: 'ok_man'; CodePoints: '1F646 200D 2642 FE0F'),
    (Name: 'ok_person'; CodePoints: '1F646'),
    (Name: 'ok_woman'; CodePoints: '1F646 200D 2640 FE0F'),
    (Name: 'old_key'; CodePoints: '1F5DD FE0F'),
    (Name: 'older_adult'; CodePoints: '1F9D3'),
    (Name: 'older_man'; CodePoints: '1F474'),
    (Name: 'older_woman'; CodePoints: '1F475'),
    (Name: 'olive'; CodePoints: '1FAD2'),
    (Name: 'om'; CodePoints: '1F549 FE0F'),
    (Name: 'oman'; CodePoints: '1F1F4 1F1F2'),
    (Name: 'on'; CodePoints: '1F51B'),
    (Name: 'oncoming_automobile'; CodePoints: '1F698'),
    (Name: 'oncoming_bus'; CodePoints: '1F68D'),
    (Name: 'oncoming_police_car'; CodePoints: '1F694'),
    (Name: 'oncoming_taxi'; CodePoints: '1F696'),
    (Name: 'one'; CodePoints: '0031 FE0F 20E3'),
    (Name: 'one_piece_swimsuit'; CodePoints: '1FA71'),
    (Name: 'onion'; CodePoints: '1F9C5'),
    (Name: 'open_book'; CodePoints: '1F4D6'),
    (Name: 'open_file_folder'; CodePoints: '1F4C2'),
    (Name: 'open_hands'; CodePoints: '1F450'),
    (Name: 'open_mouth'; CodePoints: '1F62E'),
    (Name: 'open_umbrella'; CodePoints: '2602 FE0F'),
    (Name: 'ophiuchus'; CodePoints: '26CE'),
    (Name: 'orange'; CodePoints: '1F34A'),
    (Name: 'orange_book'; CodePoints: '1F4D9'),
    (Name: 'orange_circle'; CodePoints: '1F7E0'),
    (Name: 'orange_heart'; CodePoints: '1F9E1'),
    (Name: 'orange_square'; CodePoints: '1F7E7'),
    (Name: 'orangutan'; CodePoints: '1F9A7'),
    (Name: 'orthodox_cross'; CodePoints: '2626 FE0F'),
    (Name: 'otter'; CodePoints: '1F9A6'),
    (Name: 'outbox_tray'; CodePoints: '1F4E4'),
    (Name: 'owl'; CodePoints: '1F989'),
    (Name: 'ox'; CodePoints: '1F402'),
    (Name: 'oyster'; CodePoints: '1F9AA'),
    (Name: 'package'; CodePoints: '1F4E6'),
    (Name: 'page_facing_up'; CodePoints: '1F4C4'),
    (Name: 'page_with_curl'; CodePoints: '1F4C3'),
    (Name: 'pager'; CodePoints: '1F4DF'),
    (Name: 'paintbrush'; CodePoints: '1F58C FE0F'),
    (Name: 'pakistan'; CodePoints: '1F1F5 1F1F0'),
    (Name: 'palau'; CodePoints: '1F1F5 1F1FC'),
    (Name: 'palestinian_territories'; CodePoints: '1F1F5 1F1F8'),
    (Name: 'palm_down_hand'; CodePoints: '1FAF3'),
    (Name: 'palm_tree'; CodePoints: '1F334'),
    (Name: 'palm_up_hand'; CodePoints: '1FAF4'),
    (Name: 'palms_up_together'; CodePoints: '1F932'),
    (Name: 'panama'; CodePoints: '1F1F5 1F1E6'),
    (Name: 'pancakes'; CodePoints: '1F95E'),
    (Name: 'panda_face'; CodePoints: '1F43C'),
    (Name: 'paperclip'; CodePoints: '1F4CE'),
    (Name: 'paperclips'; CodePoints: '1F587 FE0F'),
    (Name: 'papua_new_guinea'; CodePoints: '1F1F5 1F1EC'),
    (Name: 'parachute'; CodePoints: '1FA82'),
    (Name: 'paraguay'; CodePoints: '1F1F5 1F1FE'),
    (Name: 'parasol_on_ground'; CodePoints: '26F1 FE0F'),
    (Name: 'parking'; CodePoints: '1F17F FE0F'),
    (Name: 'parrot'; CodePoints: '1F99C'),
    (Name: 'part_alternation_mark'; CodePoints: '303D FE0F'),
    (Name: 'partly_sunny'; CodePoints: '26C5'),
    (Name: 'partying_face'; CodePoints: '1F973'),
    (Name: 'passenger_ship'; CodePoints: '1F6F3 FE0F'),
    (Name: 'passport_control'; CodePoints: '1F6C2'),
    (Name: 'pause_button'; CodePoints: '23F8 FE0F'),
    (Name: 'paw_prints'; CodePoints: '1F43E'),
    (Name: 'peace_symbol'; CodePoints: '262E FE0F'),
    (Name: 'peach'; CodePoints: '1F351'),
    (Name: 'peacock'; CodePoints: '1F99A'),
    (Name: 'peanuts'; CodePoints: '1F95C'),
    (Name: 'pear'; CodePoints: '1F350'),
    (Name: 'pen'; CodePoints: '1F58A FE0F'),
    (Name: 'pencil'; CodePoints: '1F4DD'),
    (Name: 'pencil2'; CodePoints: '270F FE0F'),
    (Name: 'penguin'; CodePoints: '1F427'),
    (Name: 'pensive'; CodePoints: '1F614'),
    (Name: 'people_holding_hands'; CodePoints: '1F9D1 200D 1F91D 200D 1F9D1'),
    (Name: 'people_hugging'; CodePoints: '1FAC2'),
    (Name: 'performing_arts'; CodePoints: '1F3AD'),
    (Name: 'persevere'; CodePoints: '1F623'),
    (Name: 'person_bald'; CodePoints: '1F9D1 200D 1F9B2'),
    (Name: 'person_curly_hair'; CodePoints: '1F9D1 200D 1F9B1'),
    (Name: 'person_feeding_baby'; CodePoints: '1F9D1 200D 1F37C'),
    (Name: 'person_fencing'; CodePoints: '1F93A'),
    (Name: 'person_in_manual_wheelchair'; CodePoints: '1F9D1 200D 1F9BD'),
    (Name: 'person_in_motorized_wheelchair'; CodePoints: '1F9D1 200D 1F9BC'),
    (Name: 'person_in_tuxedo'; CodePoints: '1F935'),
    (Name: 'person_red_hair'; CodePoints: '1F9D1 200D 1F9B0'),
    (Name: 'person_white_hair'; CodePoints: '1F9D1 200D 1F9B3'),
    (Name: 'person_with_crown'; CodePoints: '1FAC5'),
    (Name: 'person_with_probing_cane'; CodePoints: '1F9D1 200D 1F9AF'),
    (Name: 'person_with_turban'; CodePoints: '1F473'),
    (Name: 'person_with_veil'; CodePoints: '1F470'),
    (Name: 'peru'; CodePoints: '1F1F5 1F1EA'),
    (Name: 'petri_dish'; CodePoints: '1F9EB'),
    (Name: 'philippines'; CodePoints: '1F1F5 1F1ED'),
    (Name: 'phone'; CodePoints: '260E FE0F'),
    (Name: 'pick'; CodePoints: '26CF FE0F'),
    (Name: 'pickup_truck'; CodePoints: '1F6FB'),
    (Name: 'pie'; CodePoints: '1F967'),
    (Name: 'pig'; CodePoints: '1F437'),
    (Name: 'pig2'; CodePoints: '1F416'),
    (Name: 'pig_nose'; CodePoints: '1F43D'),
    (Name: 'pill'; CodePoints: '1F48A'),
    (Name: 'pilot'; CodePoints: '1F9D1 200D 2708 FE0F'),
    (Name: 'pinata'; CodePoints: '1FA85'),
    (Name: 'pinched_fingers'; CodePoints: '1F90C'),
    (Name: 'pinching_hand'; CodePoints: '1F90F'),
    (Name: 'pineapple'; CodePoints: '1F34D'),
    (Name: 'ping_pong'; CodePoints: '1F3D3'),
    (Name: 'pirate_flag'; CodePoints: '1F3F4 200D 2620 FE0F'),
    (Name: 'pisces'; CodePoints: '2653'),
    (Name: 'pitcairn_islands'; CodePoints: '1F1F5 1F1F3'),
    (Name: 'pizza'; CodePoints: '1F355'),
    (Name: 'placard'; CodePoints: '1FAA7'),
    (Name: 'place_of_worship'; CodePoints: '1F6D0'),
    (Name: 'plate_with_cutlery'; CodePoints: '1F37D FE0F'),
    (Name: 'play_or_pause_button'; CodePoints: '23EF FE0F'),
    (Name: 'playground_slide'; CodePoints: '1F6DD'),
    (Name: 'pleading_face'; CodePoints: '1F97A'),
    (Name: 'plunger'; CodePoints: '1FAA0'),
    (Name: 'point_down'; CodePoints: '1F447'),
    (Name: 'point_left'; CodePoints: '1F448'),
    (Name: 'point_right'; CodePoints: '1F449'),
    (Name: 'point_up'; CodePoints: '261D FE0F'),
    (Name: 'point_up_2'; CodePoints: '1F446'),
    (Name: 'poland'; CodePoints: '1F1F5 1F1F1'),
    (Name: 'polar_bear'; CodePoints: '1F43B 200D 2744 FE0F'),
    (Name: 'police_car'; CodePoints: '1F693'),
    (Name: 'police_officer'; CodePoints: '1F46E'),
    (Name: 'policeman'; CodePoints: '1F46E 200D 2642 FE0F'),
    (Name: 'policewoman'; CodePoints: '1F46E 200D 2640 FE0F'),
    (Name: 'poodle'; CodePoints: '1F429'),
    (Name: 'poop'; CodePoints: '1F4A9'),
    (Name: 'popcorn'; CodePoints: '1F37F'),
    (Name: 'portugal'; CodePoints: '1F1F5 1F1F9'),
    (Name: 'post_office'; CodePoints: '1F3E3'),
    (Name: 'postal_horn'; CodePoints: '1F4EF'),
    (Name: 'postbox'; CodePoints: '1F4EE'),
    (Name: 'potable_water'; CodePoints: '1F6B0'),
    (Name: 'potato'; CodePoints: '1F954'),
    (Name: 'potted_plant'; CodePoints: '1FAB4'),
    (Name: 'pouch'; CodePoints: '1F45D'),
    (Name: 'poultry_leg'; CodePoints: '1F357'),
    (Name: 'pound'; CodePoints: '1F4B7'),
    (Name: 'pouring_liquid'; CodePoints: '1FAD7'),
    (Name: 'pout'; CodePoints: '1F621'),
    (Name: 'pouting_cat'; CodePoints: '1F63E'),
    (Name: 'pouting_face'; CodePoints: '1F64E'),
    (Name: 'pouting_man'; CodePoints: '1F64E 200D 2642 FE0F'),
    (Name: 'pouting_woman'; CodePoints: '1F64E 200D 2640 FE0F'),
    (Name: 'pray'; CodePoints: '1F64F'),
    (Name: 'prayer_beads'; CodePoints: '1F4FF'),
    (Name: 'pregnant_man'; CodePoints: '1FAC3'),
    (Name: 'pregnant_person'; CodePoints: '1FAC4'),
    (Name: 'pregnant_woman'; CodePoints: '1F930'),
    (Name: 'pretzel'; CodePoints: '1F968'),
    (Name: 'previous_track_button'; CodePoints: '23EE FE0F'),
    (Name: 'prince'; CodePoints: '1F934'),
    (Name: 'princess'; CodePoints: '1F478'),
    (Name: 'printer'; CodePoints: '1F5A8 FE0F'),
    (Name: 'probing_cane'; CodePoints: '1F9AF'),
    (Name: 'puerto_rico'; CodePoints: '1F1F5 1F1F7'),
    (Name: 'punch'; CodePoints: '1F44A'),
    (Name: 'purple_circle'; CodePoints: '1F7E3'),
    (Name: 'purple_heart'; CodePoints: '1F49C'),
    (Name: 'purple_square'; CodePoints: '1F7EA'),
    (Name: 'purse'; CodePoints: '1F45B'),
    (Name: 'pushpin'; CodePoints: '1F4CC'),
    (Name: 'put_litter_in_its_place'; CodePoints: '1F6AE'),
    (Name: 'qatar'; CodePoints: '1F1F6 1F1E6'),
    (Name: 'question'; CodePoints: '2753'),
    (Name: 'rabbit'; CodePoints: '1F430'),
    (Name: 'rabbit2'; CodePoints: '1F407'),
    (Name: 'raccoon'; CodePoints: '1F99D'),
    (Name: 'racehorse'; CodePoints: '1F40E'),
    (Name: 'racing_car'; CodePoints: '1F3CE FE0F'),
    (Name: 'radio'; CodePoints: '1F4FB'),
    (Name: 'radio_button'; CodePoints: '1F518'),
    (Name: 'radioactive'; CodePoints: '2622 FE0F'),
    (Name: 'rage'; CodePoints: '1F621'),
    (Name: 'railway_car'; CodePoints: '1F683'),
    (Name: 'railway_track'; CodePoints: '1F6E4 FE0F'),
    (Name: 'rainbow'; CodePoints: '1F308'),
    (Name: 'rainbow_flag'; CodePoints: '1F3F3 FE0F 200D 1F308'),
    (Name: 'raised_back_of_hand'; CodePoints: '1F91A'),
    (Name: 'raised_eyebrow'; CodePoints: '1F928'),
    (Name: 'raised_hand'; CodePoints: '270B'),
    (Name: 'raised_hand_with_fingers_splayed'; CodePoints: '1F590 FE0F'),
    (Name: 'raised_hands'; CodePoints: '1F64C'),
    (Name: 'raising_hand'; CodePoints: '1F64B'),
    (Name: 'raising_hand_man'; CodePoints: '1F64B 200D 2642 FE0F'),
    (Name: 'raising_hand_woman'; CodePoints: '1F64B 200D 2640 FE0F'),
    (Name: 'ram'; CodePoints: '1F40F'),
    (Name: 'ramen'; CodePoints: '1F35C'),
    (Name: 'rat'; CodePoints: '1F400'),
    (Name: 'razor'; CodePoints: '1FA92'),
    (Name: 'receipt'; CodePoints: '1F9FE'),
    (Name: 'record_button'; CodePoints: '23FA FE0F'),
    (Name: 'recycle'; CodePoints: '267B FE0F'),
    (Name: 'red_car'; CodePoints: '1F697'),
    (Name: 'red_circle'; CodePoints: '1F534'),
    (Name: 'red_envelope'; CodePoints: '1F9E7'),
    (Name: 'red_haired_man'; CodePoints: '1F468 200D 1F9B0'),
    (Name: 'red_haired_woman'; CodePoints: '1F469 200D 1F9B0'),
    (Name: 'red_square'; CodePoints: '1F7E5'),
    (Name: 'registered'; CodePoints: '00AE FE0F'),
    (Name: 'relaxed'; CodePoints: '263A FE0F'),
    (Name: 'relieved'; CodePoints: '1F60C'),
    (Name: 'reminder_ribbon'; CodePoints: '1F397 FE0F'),
    (Name: 'repeat'; CodePoints: '1F501'),
    (Name: 'repeat_one'; CodePoints: '1F502'),
    (Name: 'rescue_worker_helmet'; CodePoints: '26D1 FE0F'),
    (Name: 'restroom'; CodePoints: '1F6BB'),
    (Name: 'reunion'; CodePoints: '1F1F7 1F1EA'),
    (Name: 'revolving_hearts'; CodePoints: '1F49E'),
    (Name: 'rewind'; CodePoints: '23EA'),
    (Name: 'rhinoceros'; CodePoints: '1F98F'),
    (Name: 'ribbon'; CodePoints: '1F380'),
    (Name: 'rice'; CodePoints: '1F35A'),
    (Name: 'rice_ball'; CodePoints: '1F359'),
    (Name: 'rice_cracker'; CodePoints: '1F358'),
    (Name: 'rice_scene'; CodePoints: '1F391'),
    (Name: 'right_anger_bubble'; CodePoints: '1F5EF FE0F'),
    (Name: 'rightwards_hand'; CodePoints: '1FAF1'),
    (Name: 'ring'; CodePoints: '1F48D'),
    (Name: 'ring_buoy'; CodePoints: '1F6DF'),
    (Name: 'ringed_planet'; CodePoints: '1FA90'),
    (Name: 'robot'; CodePoints: '1F916'),
    (Name: 'rock'; CodePoints: '1FAA8'),
    (Name: 'rocket'; CodePoints: '1F680'),
    (Name: 'rofl'; CodePoints: '1F923'),
    (Name: 'roll_eyes'; CodePoints: '1F644'),
    (Name: 'roll_of_paper'; CodePoints: '1F9FB'),
    (Name: 'roller_coaster'; CodePoints: '1F3A2'),
    (Name: 'roller_skate'; CodePoints: '1F6FC'),
    (Name: 'romania'; CodePoints: '1F1F7 1F1F4'),
    (Name: 'rooster'; CodePoints: '1F413'),
    (Name: 'rose'; CodePoints: '1F339'),
    (Name: 'rosette'; CodePoints: '1F3F5 FE0F'),
    (Name: 'rotating_light'; CodePoints: '1F6A8'),
    (Name: 'round_pushpin'; CodePoints: '1F4CD'),
    (Name: 'rowboat'; CodePoints: '1F6A3'),
    (Name: 'rowing_man'; CodePoints: '1F6A3 200D 2642 FE0F'),
    (Name: 'rowing_woman'; CodePoints: '1F6A3 200D 2640 FE0F'),
    (Name: 'ru'; CodePoints: '1F1F7 1F1FA'),
    (Name: 'rugby_football'; CodePoints: '1F3C9'),
    (Name: 'runner'; CodePoints: '1F3C3'),
    (Name: 'running'; CodePoints: '1F3C3'),
    (Name: 'running_man'; CodePoints: '1F3C3 200D 2642 FE0F'),
    (Name: 'running_shirt_with_sash'; CodePoints: '1F3BD'),
    (Name: 'running_woman'; CodePoints: '1F3C3 200D 2640 FE0F'),
    (Name: 'rwanda'; CodePoints: '1F1F7 1F1FC'),
    (Name: 'sa'; CodePoints: '1F202 FE0F'),
    (Name: 'safety_pin'; CodePoints: '1F9F7'),
    (Name: 'safety_vest'; CodePoints: '1F9BA'),
    (Name: 'sagittarius'; CodePoints: '2650'),
    (Name: 'sailboat'; CodePoints: '26F5'),
    (Name: 'sake'; CodePoints: '1F376'),
    (Name: 'salt'; CodePoints: '1F9C2'),
    (Name: 'saluting_face'; CodePoints: '1FAE1'),
    (Name: 'samoa'; CodePoints: '1F1FC 1F1F8'),
    (Name: 'san_marino'; CodePoints: '1F1F8 1F1F2'),
    (Name: 'sandal'; CodePoints: '1F461'),
    (Name: 'sandwich'; CodePoints: '1F96A'),
    (Name: 'santa'; CodePoints: '1F385'),
    (Name: 'sao_tome_principe'; CodePoints: '1F1F8 1F1F9'),
    (Name: 'sari'; CodePoints: '1F97B'),
    (Name: 'sassy_man'; CodePoints: '1F481 200D 2642 FE0F'),
    (Name: 'sassy_woman'; CodePoints: '1F481 200D 2640 FE0F'),
    (Name: 'satellite'; CodePoints: '1F4E1'),
    (Name: 'satisfied'; CodePoints: '1F606'),
    (Name: 'saudi_arabia'; CodePoints: '1F1F8 1F1E6'),
    (Name: 'sauna_man'; CodePoints: '1F9D6 200D 2642 FE0F'),
    (Name: 'sauna_person'; CodePoints: '1F9D6'),
    (Name: 'sauna_woman'; CodePoints: '1F9D6 200D 2640 FE0F'),
    (Name: 'sauropod'; CodePoints: '1F995'),
    (Name: 'saxophone'; CodePoints: '1F3B7'),
    (Name: 'scarf'; CodePoints: '1F9E3'),
    (Name: 'school'; CodePoints: '1F3EB'),
    (Name: 'school_satchel'; CodePoints: '1F392'),
    (Name: 'scientist'; CodePoints: '1F9D1 200D 1F52C'),
    (Name: 'scissors'; CodePoints: '2702 FE0F'),
    (Name: 'scorpion'; CodePoints: '1F982'),
    (Name: 'scorpius'; CodePoints: '264F'),
    (Name: 'scotland'; CodePoints: '1F3F4 E0067 E0062 E0073 E0063 E0074 E007F'),
    (Name: 'scream'; CodePoints: '1F631'),
    (Name: 'scream_cat'; CodePoints: '1F640'),
    (Name: 'screwdriver'; CodePoints: '1FA9B'),
    (Name: 'scroll'; CodePoints: '1F4DC'),
    (Name: 'seal'; CodePoints: '1F9AD'),
    (Name: 'seat'; CodePoints: '1F4BA'),
    (Name: 'secret'; CodePoints: '3299 FE0F'),
    (Name: 'see_no_evil'; CodePoints: '1F648'),
    (Name: 'seedling'; CodePoints: '1F331'),
    (Name: 'selfie'; CodePoints: '1F933'),
    (Name: 'senegal'; CodePoints: '1F1F8 1F1F3'),
    (Name: 'serbia'; CodePoints: '1F1F7 1F1F8'),
    (Name: 'service_dog'; CodePoints: '1F415 200D 1F9BA'),
    (Name: 'seven'; CodePoints: '0037 FE0F 20E3'),
    (Name: 'sewing_needle'; CodePoints: '1FAA1'),
    (Name: 'seychelles'; CodePoints: '1F1F8 1F1E8'),
    (Name: 'shallow_pan_of_food'; CodePoints: '1F958'),
    (Name: 'shamrock'; CodePoints: '2618 FE0F'),
    (Name: 'shark'; CodePoints: '1F988'),
    (Name: 'shaved_ice'; CodePoints: '1F367'),
    (Name: 'sheep'; CodePoints: '1F411'),
    (Name: 'shell'; CodePoints: '1F41A'),
    (Name: 'shield'; CodePoints: '1F6E1 FE0F'),
    (Name: 'shinto_shrine'; CodePoints: '26E9 FE0F'),
    (Name: 'ship'; CodePoints: '1F6A2'),
    (Name: 'shirt'; CodePoints: '1F455'),
    (Name: 'shit'; CodePoints: '1F4A9'),
    (Name: 'shoe'; CodePoints: '1F45E'),
    (Name: 'shopping'; CodePoints: '1F6CD FE0F'),
    (Name: 'shopping_cart'; CodePoints: '1F6D2'),
    (Name: 'shorts'; CodePoints: '1FA73'),
    (Name: 'shower'; CodePoints: '1F6BF'),
    (Name: 'shrimp'; CodePoints: '1F990'),
    (Name: 'shrug'; CodePoints: '1F937'),
    (Name: 'shushing_face'; CodePoints: '1F92B'),
    (Name: 'sierra_leone'; CodePoints: '1F1F8 1F1F1'),
    (Name: 'signal_strength'; CodePoints: '1F4F6'),
    (Name: 'singapore'; CodePoints: '1F1F8 1F1EC'),
    (Name: 'singer'; CodePoints: '1F9D1 200D 1F3A4'),
    (Name: 'sint_maarten'; CodePoints: '1F1F8 1F1FD'),
    (Name: 'six'; CodePoints: '0036 FE0F 20E3'),
    (Name: 'six_pointed_star'; CodePoints: '1F52F'),
    (Name: 'skateboard'; CodePoints: '1F6F9'),
    (Name: 'ski'; CodePoints: '1F3BF'),
    (Name: 'skier'; CodePoints: '26F7 FE0F'),
    (Name: 'skull'; CodePoints: '1F480'),
    (Name: 'skull_and_crossbones'; CodePoints: '2620 FE0F'),
    (Name: 'skunk'; CodePoints: '1F9A8'),
    (Name: 'sled'; CodePoints: '1F6F7'),
    (Name: 'sleeping'; CodePoints: '1F634'),
    (Name: 'sleeping_bed'; CodePoints: '1F6CC'),
    (Name: 'sleepy'; CodePoints: '1F62A'),
    (Name: 'slightly_frowning_face'; CodePoints: '1F641'),
    (Name: 'slightly_smiling_face'; CodePoints: '1F642'),
    (Name: 'slot_machine'; CodePoints: '1F3B0'),
    (Name: 'sloth'; CodePoints: '1F9A5'),
    (Name: 'slovakia'; CodePoints: '1F1F8 1F1F0'),
    (Name: 'slovenia'; CodePoints: '1F1F8 1F1EE'),
    (Name: 'small_airplane'; CodePoints: '1F6E9 FE0F'),
    (Name: 'small_blue_diamond'; CodePoints: '1F539'),
    (Name: 'small_orange_diamond'; CodePoints: '1F538'),
    (Name: 'small_red_triangle'; CodePoints: '1F53A'),
    (Name: 'small_red_triangle_down'; CodePoints: '1F53B'),
    (Name: 'smile'; CodePoints: '1F604'),
    (Name: 'smile_cat'; CodePoints: '1F638'),
    (Name: 'smiley'; CodePoints: '1F603'),
    (Name: 'smiley_cat'; CodePoints: '1F63A'),
    (Name: 'smiling_face_with_tear'; CodePoints: '1F972'),
    (Name: 'smiling_face_with_three_hearts'; CodePoints: '1F970'),
    (Name: 'smiling_imp'; CodePoints: '1F608'),
    (Name: 'smirk'; CodePoints: '1F60F'),
    (Name: 'smirk_cat'; CodePoints: '1F63C'),
    (Name: 'smoking'; CodePoints: '1F6AC'),
    (Name: 'snail'; CodePoints: '1F40C'),
    (Name: 'snake'; CodePoints: '1F40D'),
    (Name: 'sneezing_face'; CodePoints: '1F927'),
    (Name: 'snowboarder'; CodePoints: '1F3C2'),
    (Name: 'snowflake'; CodePoints: '2744 FE0F'),
    (Name: 'snowman'; CodePoints: '26C4'),
    (Name: 'snowman_with_snow'; CodePoints: '2603 FE0F'),
    (Name: 'soap'; CodePoints: '1F9FC'),
    (Name: 'sob'; CodePoints: '1F62D'),
    (Name: 'soccer'; CodePoints: '26BD'),
    (Name: 'socks'; CodePoints: '1F9E6'),
    (Name: 'softball'; CodePoints: '1F94E'),
    (Name: 'solomon_islands'; CodePoints: '1F1F8 1F1E7'),
    (Name: 'somalia'; CodePoints: '1F1F8 1F1F4'),
    (Name: 'soon'; CodePoints: '1F51C'),
    (Name: 'sos'; CodePoints: '1F198'),
    (Name: 'sound'; CodePoints: '1F509'),
    (Name: 'south_africa'; CodePoints: '1F1FF 1F1E6'),
    (Name: 'south_georgia_south_sandwich_islands'; CodePoints: '1F1EC 1F1F8'),
    (Name: 'south_sudan'; CodePoints: '1F1F8 1F1F8'),
    (Name: 'space_invader'; CodePoints: '1F47E'),
    (Name: 'spades'; CodePoints: '2660 FE0F'),
    (Name: 'spaghetti'; CodePoints: '1F35D'),
    (Name: 'sparkle'; CodePoints: '2747 FE0F'),
    (Name: 'sparkler'; CodePoints: '1F387'),
    (Name: 'sparkles'; CodePoints: '2728'),
    (Name: 'sparkling_heart'; CodePoints: '1F496'),
    (Name: 'speak_no_evil'; CodePoints: '1F64A'),
    (Name: 'speaker'; CodePoints: '1F508'),
    (Name: 'speaking_head'; CodePoints: '1F5E3 FE0F'),
    (Name: 'speech_balloon'; CodePoints: '1F4AC'),
    (Name: 'speedboat'; CodePoints: '1F6A4'),
    (Name: 'spider'; CodePoints: '1F577 FE0F'),
    (Name: 'spider_web'; CodePoints: '1F578 FE0F'),
    (Name: 'spiral_calendar'; CodePoints: '1F5D3 FE0F'),
    (Name: 'spiral_notepad'; CodePoints: '1F5D2 FE0F'),
    (Name: 'sponge'; CodePoints: '1F9FD'),
    (Name: 'spoon'; CodePoints: '1F944'),
    (Name: 'squid'; CodePoints: '1F991'),
    (Name: 'sri_lanka'; CodePoints: '1F1F1 1F1F0'),
    (Name: 'st_barthelemy'; CodePoints: '1F1E7 1F1F1'),
    (Name: 'st_helena'; CodePoints: '1F1F8 1F1ED'),
    (Name: 'st_kitts_nevis'; CodePoints: '1F1F0 1F1F3'),
    (Name: 'st_lucia'; CodePoints: '1F1F1 1F1E8'),
    (Name: 'st_martin'; CodePoints: '1F1F2 1F1EB'),
    (Name: 'st_pierre_miquelon'; CodePoints: '1F1F5 1F1F2'),
    (Name: 'st_vincent_grenadines'; CodePoints: '1F1FB 1F1E8'),
    (Name: 'stadium'; CodePoints: '1F3DF FE0F'),
    (Name: 'standing_man'; CodePoints: '1F9CD 200D 2642 FE0F'),
    (Name: 'standing_person'; CodePoints: '1F9CD'),
    (Name: 'standing_woman'; CodePoints: '1F9CD 200D 2640 FE0F'),
    (Name: 'star'; CodePoints: '2B50'),
    (Name: 'star2'; CodePoints: '1F31F'),
    (Name: 'star_and_crescent'; CodePoints: '262A FE0F'),
    (Name: 'star_of_david'; CodePoints: '2721 FE0F'),
    (Name: 'star_struck'; CodePoints: '1F929'),
    (Name: 'stars'; CodePoints: '1F320'),
    (Name: 'station'; CodePoints: '1F689'),
    (Name: 'statue_of_liberty'; CodePoints: '1F5FD'),
    (Name: 'steam_locomotive'; CodePoints: '1F682'),
    (Name: 'stethoscope'; CodePoints: '1FA7A'),
    (Name: 'stew'; CodePoints: '1F372'),
    (Name: 'stop_button'; CodePoints: '23F9 FE0F'),
    (Name: 'stop_sign'; CodePoints: '1F6D1'),
    (Name: 'stopwatch'; CodePoints: '23F1 FE0F'),
    (Name: 'straight_ruler'; CodePoints: '1F4CF'),
    (Name: 'strawberry'; CodePoints: '1F353'),
    (Name: 'stuck_out_tongue'; CodePoints: '1F61B'),
    (Name: 'stuck_out_tongue_closed_eyes'; CodePoints: '1F61D'),
    (Name: 'stuck_out_tongue_winking_eye'; CodePoints: '1F61C'),
    (Name: 'student'; CodePoints: '1F9D1 200D 1F393'),
    (Name: 'studio_microphone'; CodePoints: '1F399 FE0F'),
    (Name: 'stuffed_flatbread'; CodePoints: '1F959'),
    (Name: 'sudan'; CodePoints: '1F1F8 1F1E9'),
    (Name: 'sun_behind_large_cloud'; CodePoints: '1F325 FE0F'),
    (Name: 'sun_behind_rain_cloud'; CodePoints: '1F326 FE0F'),
    (Name: 'sun_behind_small_cloud'; CodePoints: '1F324 FE0F'),
    (Name: 'sun_with_face'; CodePoints: '1F31E'),
    (Name: 'sunflower'; CodePoints: '1F33B'),
    (Name: 'sunglasses'; CodePoints: '1F60E'),
    (Name: 'sunny'; CodePoints: '2600 FE0F'),
    (Name: 'sunrise'; CodePoints: '1F305'),
    (Name: 'sunrise_over_mountains'; CodePoints: '1F304'),
    (Name: 'superhero'; CodePoints: '1F9B8'),
    (Name: 'superhero_man'; CodePoints: '1F9B8 200D 2642 FE0F'),
    (Name: 'superhero_woman'; CodePoints: '1F9B8 200D 2640 FE0F'),
    (Name: 'supervillain'; CodePoints: '1F9B9'),
    (Name: 'supervillain_man'; CodePoints: '1F9B9 200D 2642 FE0F'),
    (Name: 'supervillain_woman'; CodePoints: '1F9B9 200D 2640 FE0F'),
    (Name: 'surfer'; CodePoints: '1F3C4'),
    (Name: 'surfing_man'; CodePoints: '1F3C4 200D 2642 FE0F'),
    (Name: 'surfing_woman'; CodePoints: '1F3C4 200D 2640 FE0F'),
    (Name: 'suriname'; CodePoints: '1F1F8 1F1F7'),
    (Name: 'sushi'; CodePoints: '1F363'),
    (Name: 'suspension_railway'; CodePoints: '1F69F'),
    (Name: 'svalbard_jan_mayen'; CodePoints: '1F1F8 1F1EF'),
    (Name: 'swan'; CodePoints: '1F9A2'),
    (Name: 'swaziland'; CodePoints: '1F1F8 1F1FF'),
    (Name: 'sweat'; CodePoints: '1F613'),
    (Name: 'sweat_drops'; CodePoints: '1F4A6'),
    (Name: 'sweat_smile'; CodePoints: '1F605'),
    (Name: 'sweden'; CodePoints: '1F1F8 1F1EA'),
    (Name: 'sweet_potato'; CodePoints: '1F360'),
    (Name: 'swim_brief'; CodePoints: '1FA72'),
    (Name: 'swimmer'; CodePoints: '1F3CA'),
    (Name: 'swimming_man'; CodePoints: '1F3CA 200D 2642 FE0F'),
    (Name: 'swimming_woman'; CodePoints: '1F3CA 200D 2640 FE0F'),
    (Name: 'switzerland'; CodePoints: '1F1E8 1F1ED'),
    (Name: 'symbols'; CodePoints: '1F523'),
    (Name: 'synagogue'; CodePoints: '1F54D'),
    (Name: 'syria'; CodePoints: '1F1F8 1F1FE'),
    (Name: 'syringe'; CodePoints: '1F489'),
    (Name: 't-rex'; CodePoints: '1F996'),
    (Name: 'taco'; CodePoints: '1F32E'),
    (Name: 'tada'; CodePoints: '1F389'),
    (Name: 'taiwan'; CodePoints: '1F1F9 1F1FC'),
    (Name: 'tajikistan'; CodePoints: '1F1F9 1F1EF'),
    (Name: 'takeout_box'; CodePoints: '1F961'),
    (Name: 'tamale'; CodePoints: '1FAD4'),
    (Name: 'tanabata_tree'; CodePoints: '1F38B'),
    (Name: 'tangerine'; CodePoints: '1F34A'),
    (Name: 'tanzania'; CodePoints: '1F1F9 1F1FF'),
    (Name: 'taurus'; CodePoints: '2649'),
    (Name: 'taxi'; CodePoints: '1F695'),
    (Name: 'tea'; CodePoints: '1F375'),
    (Name: 'teacher'; CodePoints: '1F9D1 200D 1F3EB'),
    (Name: 'teapot'; CodePoints: '1FAD6'),
    (Name: 'technologist'; CodePoints: '1F9D1 200D 1F4BB'),
    (Name: 'teddy_bear'; CodePoints: '1F9F8'),
    (Name: 'telephone'; CodePoints: '260E FE0F'),
    (Name: 'telephone_receiver'; CodePoints: '1F4DE'),
    (Name: 'telescope'; CodePoints: '1F52D'),
    (Name: 'tennis'; CodePoints: '1F3BE'),
    (Name: 'tent'; CodePoints: '26FA'),
    (Name: 'test_tube'; CodePoints: '1F9EA'),
    (Name: 'thailand'; CodePoints: '1F1F9 1F1ED'),
    (Name: 'thermometer'; CodePoints: '1F321 FE0F'),
    (Name: 'thinking'; CodePoints: '1F914'),
    (Name: 'thong_sandal'; CodePoints: '1FA74'),
    (Name: 'thought_balloon'; CodePoints: '1F4AD'),
    (Name: 'thread'; CodePoints: '1F9F5'),
    (Name: 'three'; CodePoints: '0033 FE0F 20E3'),
    (Name: 'thumbsdown'; CodePoints: '1F44E'),
    (Name: 'thumbsup'; CodePoints: '1F44D'),
    (Name: 'ticket'; CodePoints: '1F3AB'),
    (Name: 'tickets'; CodePoints: '1F39F FE0F'),
    (Name: 'tiger'; CodePoints: '1F42F'),
    (Name: 'tiger2'; CodePoints: '1F405'),
    (Name: 'timer_clock'; CodePoints: '23F2 FE0F'),
    (Name: 'timor_leste'; CodePoints: '1F1F9 1F1F1'),
    (Name: 'tipping_hand_man'; CodePoints: '1F481 200D 2642 FE0F'),
    (Name: 'tipping_hand_person'; CodePoints: '1F481'),
    (Name: 'tipping_hand_woman'; CodePoints: '1F481 200D 2640 FE0F'),
    (Name: 'tired_face'; CodePoints: '1F62B'),
    (Name: 'tm'; CodePoints: '2122 FE0F'),
    (Name: 'togo'; CodePoints: '1F1F9 1F1EC'),
    (Name: 'toilet'; CodePoints: '1F6BD'),
    (Name: 'tokelau'; CodePoints: '1F1F9 1F1F0'),
    (Name: 'tokyo_tower'; CodePoints: '1F5FC'),
    (Name: 'tomato'; CodePoints: '1F345'),
    (Name: 'tonga'; CodePoints: '1F1F9 1F1F4'),
    (Name: 'tongue'; CodePoints: '1F445'),
    (Name: 'toolbox'; CodePoints: '1F9F0'),
    (Name: 'tooth'; CodePoints: '1F9B7'),
    (Name: 'toothbrush'; CodePoints: '1FAA5'),
    (Name: 'top'; CodePoints: '1F51D'),
    (Name: 'tophat'; CodePoints: '1F3A9'),
    (Name: 'tornado'; CodePoints: '1F32A FE0F'),
    (Name: 'tr'; CodePoints: '1F1F9 1F1F7'),
    (Name: 'trackball'; CodePoints: '1F5B2 FE0F'),
    (Name: 'tractor'; CodePoints: '1F69C'),
    (Name: 'traffic_light'; CodePoints: '1F6A5'),
    (Name: 'train'; CodePoints: '1F68B'),
    (Name: 'train2'; CodePoints: '1F686'),
    (Name: 'tram'; CodePoints: '1F68A'),
    (Name: 'transgender_flag'; CodePoints: '1F3F3 FE0F 200D 26A7 FE0F'),
    (Name: 'transgender_symbol'; CodePoints: '26A7 FE0F'),
    (Name: 'triangular_flag_on_post'; CodePoints: '1F6A9'),
    (Name: 'triangular_ruler'; CodePoints: '1F4D0'),
    (Name: 'trident'; CodePoints: '1F531'),
    (Name: 'trinidad_tobago'; CodePoints: '1F1F9 1F1F9'),
    (Name: 'tristan_da_cunha'; CodePoints: '1F1F9 1F1E6'),
    (Name: 'triumph'; CodePoints: '1F624'),
    (Name: 'troll'; CodePoints: '1F9CC'),
    (Name: 'trolleybus'; CodePoints: '1F68E'),
    (Name: 'trophy'; CodePoints: '1F3C6'),
    (Name: 'tropical_drink'; CodePoints: '1F379'),
    (Name: 'tropical_fish'; CodePoints: '1F420'),
    (Name: 'truck'; CodePoints: '1F69A'),
    (Name: 'trumpet'; CodePoints: '1F3BA'),
    (Name: 'tshirt'; CodePoints: '1F455'),
    (Name: 'tulip'; CodePoints: '1F337'),
    (Name: 'tumbler_glass'; CodePoints: '1F943'),
    (Name: 'tunisia'; CodePoints: '1F1F9 1F1F3'),
    (Name: 'turkey'; CodePoints: '1F983'),
    (Name: 'turkmenistan'; CodePoints: '1F1F9 1F1F2'),
    (Name: 'turks_caicos_islands'; CodePoints: '1F1F9 1F1E8'),
    (Name: 'turtle'; CodePoints: '1F422'),
    (Name: 'tuvalu'; CodePoints: '1F1F9 1F1FB'),
    (Name: 'tv'; CodePoints: '1F4FA'),
    (Name: 'twisted_rightwards_arrows'; CodePoints: '1F500'),
    (Name: 'two'; CodePoints: '0032 FE0F 20E3'),
    (Name: 'two_hearts'; CodePoints: '1F495'),
    (Name: 'two_men_holding_hands'; CodePoints: '1F46C'),
    (Name: 'two_women_holding_hands'; CodePoints: '1F46D'),
    (Name: 'u5272'; CodePoints: '1F239'),
    (Name: 'u5408'; CodePoints: '1F234'),
    (Name: 'u55b6'; CodePoints: '1F23A'),
    (Name: 'u6307'; CodePoints: '1F22F'),
    (Name: 'u6708'; CodePoints: '1F237 FE0F'),
    (Name: 'u6709'; CodePoints: '1F236'),
    (Name: 'u6e80'; CodePoints: '1F235'),
    (Name: 'u7121'; CodePoints: '1F21A'),
    (Name: 'u7533'; CodePoints: '1F238'),
    (Name: 'u7981'; CodePoints: '1F232'),
    (Name: 'u7a7a'; CodePoints: '1F233'),
    (Name: 'uganda'; CodePoints: '1F1FA 1F1EC'),
    (Name: 'uk'; CodePoints: '1F1EC 1F1E7'),
    (Name: 'ukraine'; CodePoints: '1F1FA 1F1E6'),
    (Name: 'umbrella'; CodePoints: '2614'),
    (Name: 'unamused'; CodePoints: '1F612'),
    (Name: 'underage'; CodePoints: '1F51E'),
    (Name: 'unicorn'; CodePoints: '1F984'),
    (Name: 'united_arab_emirates'; CodePoints: '1F1E6 1F1EA'),
    (Name: 'united_nations'; CodePoints: '1F1FA 1F1F3'),
    (Name: 'unlock'; CodePoints: '1F513'),
    (Name: 'up'; CodePoints: '1F199'),
    (Name: 'upside_down_face'; CodePoints: '1F643'),
    (Name: 'uruguay'; CodePoints: '1F1FA 1F1FE'),
    (Name: 'us'; CodePoints: '1F1FA 1F1F8'),
    (Name: 'us_outlying_islands'; CodePoints: '1F1FA 1F1F2'),
    (Name: 'us_virgin_islands'; CodePoints: '1F1FB 1F1EE'),
    (Name: 'uzbekistan'; CodePoints: '1F1FA 1F1FF'),
    (Name: 'v'; CodePoints: '270C FE0F'),
    (Name: 'vampire'; CodePoints: '1F9DB'),
    (Name: 'vampire_man'; CodePoints: '1F9DB 200D 2642 FE0F'),
    (Name: 'vampire_woman'; CodePoints: '1F9DB 200D 2640 FE0F'),
    (Name: 'vanuatu'; CodePoints: '1F1FB 1F1FA'),
    (Name: 'vatican_city'; CodePoints: '1F1FB 1F1E6'),
    (Name: 'venezuela'; CodePoints: '1F1FB 1F1EA'),
    (Name: 'vertical_traffic_light'; CodePoints: '1F6A6'),
    (Name: 'vhs'; CodePoints: '1F4FC'),
    (Name: 'vibration_mode'; CodePoints: '1F4F3'),
    (Name: 'video_camera'; CodePoints: '1F4F9'),
    (Name: 'video_game'; CodePoints: '1F3AE'),
    (Name: 'vietnam'; CodePoints: '1F1FB 1F1F3'),
    (Name: 'violin'; CodePoints: '1F3BB'),
    (Name: 'virgo'; CodePoints: '264D'),
    (Name: 'volcano'; CodePoints: '1F30B'),
    (Name: 'volleyball'; CodePoints: '1F3D0'),
    (Name: 'vomiting_face'; CodePoints: '1F92E'),
    (Name: 'vs'; CodePoints: '1F19A'),
    (Name: 'vulcan_salute'; CodePoints: '1F596'),
    (Name: 'waffle'; CodePoints: '1F9C7'),
    (Name: 'wales'; CodePoints: '1F3F4 E0067 E0062 E0077 E006C E0073 E007F'),
    (Name: 'walking'; CodePoints: '1F6B6'),
    (Name: 'walking_man'; CodePoints: '1F6B6 200D 2642 FE0F'),
    (Name: 'walking_woman'; CodePoints: '1F6B6 200D 2640 FE0F'),
    (Name: 'wallis_futuna'; CodePoints: '1F1FC 1F1EB'),
    (Name: 'waning_crescent_moon'; CodePoints: '1F318'),
    (Name: 'waning_gibbous_moon'; CodePoints: '1F316'),
    (Name: 'warning'; CodePoints: '26A0 FE0F'),
    (Name: 'wastebasket'; CodePoints: '1F5D1 FE0F'),
    (Name: 'watch'; CodePoints: '231A'),
    (Name: 'water_buffalo'; CodePoints: '1F403'),
    (Name: 'water_polo'; CodePoints: '1F93D'),
    (Name: 'watermelon'; CodePoints: '1F349'),
    (Name: 'wave'; CodePoints: '1F44B'),
    (Name: 'wavy_dash'; CodePoints: '3030 FE0F'),
    (Name: 'waxing_crescent_moon'; CodePoints: '1F312'),
    (Name: 'waxing_gibbous_moon'; CodePoints: '1F314'),
    (Name: 'wc'; CodePoints: '1F6BE'),
    (Name: 'weary'; CodePoints: '1F629'),
    (Name: 'wedding'; CodePoints: '1F492'),
    (Name: 'weight_lifting'; CodePoints: '1F3CB FE0F'),
    (Name: 'weight_lifting_man'; CodePoints: '1F3CB FE0F 200D 2642 FE0F'),
    (Name: 'weight_lifting_woman'; CodePoints: '1F3CB FE0F 200D 2640 FE0F'),
    (Name: 'western_sahara'; CodePoints: '1F1EA 1F1ED'),
    (Name: 'whale'; CodePoints: '1F433'),
    (Name: 'whale2'; CodePoints: '1F40B'),
    (Name: 'wheel'; CodePoints: '1F6DE'),
    (Name: 'wheel_of_dharma'; CodePoints: '2638 FE0F'),
    (Name: 'wheelchair'; CodePoints: '267F'),
    (Name: 'white_check_mark'; CodePoints: '2705'),
    (Name: 'white_circle'; CodePoints: '26AA'),
    (Name: 'white_flag'; CodePoints: '1F3F3 FE0F'),
    (Name: 'white_flower'; CodePoints: '1F4AE'),
    (Name: 'white_haired_man'; CodePoints: '1F468 200D 1F9B3'),
    (Name: 'white_haired_woman'; CodePoints: '1F469 200D 1F9B3'),
    (Name: 'white_heart'; CodePoints: '1F90D'),
    (Name: 'white_large_square'; CodePoints: '2B1C'),
    (Name: 'white_medium_small_square'; CodePoints: '25FD'),
    (Name: 'white_medium_square'; CodePoints: '25FB FE0F'),
    (Name: 'white_small_square'; CodePoints: '25AB FE0F'),
    (Name: 'white_square_button'; CodePoints: '1F533'),
    (Name: 'wilted_flower'; CodePoints: '1F940'),
    (Name: 'wind_chime'; CodePoints: '1F390'),
    (Name: 'wind_face'; CodePoints: '1F32C FE0F'),
    (Name: 'window'; CodePoints: '1FA9F'),
    (Name: 'wine_glass'; CodePoints: '1F377'),
    (Name: 'wink'; CodePoints: '1F609'),
    (Name: 'wolf'; CodePoints: '1F43A'),
    (Name: 'woman'; CodePoints: '1F469'),
    (Name: 'woman_artist'; CodePoints: '1F469 200D 1F3A8'),
    (Name: 'woman_astronaut'; CodePoints: '1F469 200D 1F680'),
    (Name: 'woman_beard'; CodePoints: '1F9D4 200D 2640 FE0F'),
    (Name: 'woman_cartwheeling'; CodePoints: '1F938 200D 2640 FE0F'),
    (Name: 'woman_cook'; CodePoints: '1F469 200D 1F373'),
    (Name: 'woman_dancing'; CodePoints: '1F483'),
    (Name: 'woman_facepalming'; CodePoints: '1F926 200D 2640 FE0F'),
    (Name: 'woman_factory_worker'; CodePoints: '1F469 200D 1F3ED'),
    (Name: 'woman_farmer'; CodePoints: '1F469 200D 1F33E'),
    (Name: 'woman_feeding_baby'; CodePoints: '1F469 200D 1F37C'),
    (Name: 'woman_firefighter'; CodePoints: '1F469 200D 1F692'),
    (Name: 'woman_health_worker'; CodePoints: '1F469 200D 2695 FE0F'),
    (Name: 'woman_in_manual_wheelchair'; CodePoints: '1F469 200D 1F9BD'),
    (Name: 'woman_in_motorized_wheelchair'; CodePoints: '1F469 200D 1F9BC'),
    (Name: 'woman_in_tuxedo'; CodePoints: '1F935 200D 2640 FE0F'),
    (Name: 'woman_judge'; CodePoints: '1F469 200D 2696 FE0F'),
    (Name: 'woman_juggling'; CodePoints: '1F939 200D 2640 FE0F'),
    (Name: 'woman_mechanic'; CodePoints: '1F469 200D 1F527'),
    (Name: 'woman_office_worker'; CodePoints: '1F469 200D 1F4BC'),
    (Name: 'woman_pilot'; CodePoints: '1F469 200D 2708 FE0F'),
    (Name: 'woman_playing_handball'; CodePoints: '1F93E 200D 2640 FE0F'),
    (Name: 'woman_playing_water_polo'; CodePoints: '1F93D 200D 2640 FE0F'),
    (Name: 'woman_scientist'; CodePoints: '1F469 200D 1F52C'),
    (Name: 'woman_shrugging'; CodePoints: '1F937 200D 2640 FE0F'),
    (Name: 'woman_singer'; CodePoints: '1F469 200D 1F3A4'),
    (Name: 'woman_student'; CodePoints: '1F469 200D 1F393'),
    (Name: 'woman_teacher'; CodePoints: '1F469 200D 1F3EB'),
    (Name: 'woman_technologist'; CodePoints: '1F469 200D 1F4BB'),
    (Name: 'woman_with_headscarf'; CodePoints: '1F9D5'),
    (Name: 'woman_with_probing_cane'; CodePoints: '1F469 200D 1F9AF'),
    (Name: 'woman_with_turban'; CodePoints: '1F473 200D 2640 FE0F'),
    (Name: 'woman_with_veil'; CodePoints: '1F470 200D 2640 FE0F'),
    (Name: 'womans_clothes'; CodePoints: '1F45A'),
    (Name: 'womans_hat'; CodePoints: '1F452'),
    (Name: 'women_wrestling'; CodePoints: '1F93C 200D 2640 FE0F'),
    (Name: 'womens'; CodePoints: '1F6BA'),
    (Name: 'wood'; CodePoints: '1FAB5'),
    (Name: 'woozy_face'; CodePoints: '1F974'),
    (Name: 'world_map'; CodePoints: '1F5FA FE0F'),
    (Name: 'worm'; CodePoints: '1FAB1'),
    (Name: 'worried'; CodePoints: '1F61F'),
    (Name: 'wrench'; CodePoints: '1F527'),
    (Name: 'wrestling'; CodePoints: '1F93C'),
    (Name: 'writing_hand'; CodePoints: '270D FE0F'),
    (Name: 'x'; CodePoints: '274C'),
    (Name: 'x_ray'; CodePoints: '1FA7B'),
    (Name: 'yarn'; CodePoints: '1F9F6'),
    (Name: 'yawning_face'; CodePoints: '1F971'),
    (Name: 'yellow_circle'; CodePoints: '1F7E1'),
    (Name: 'yellow_heart'; CodePoints: '1F49B'),
    (Name: 'yellow_square'; CodePoints: '1F7E8'),
    (Name: 'yemen'; CodePoints: '1F1FE 1F1EA'),
    (Name: 'yen'; CodePoints: '1F4B4'),
    (Name: 'yin_yang'; CodePoints: '262F FE0F'),
    (Name: 'yo_yo'; CodePoints: '1FA80'),
    (Name: 'yum'; CodePoints: '1F60B'),
    (Name: 'zambia'; CodePoints: '1F1FF 1F1F2'),
    (Name: 'zany_face'; CodePoints: '1F92A'),
    (Name: 'zap'; CodePoints: '26A1'),
    (Name: 'zebra'; CodePoints: '1F993'),
    (Name: 'zero'; CodePoints: '0030 FE0F 20E3'),
    (Name: 'zimbabwe'; CodePoints: '1F1FF 1F1FC'),
    (Name: 'zipper_mouth_face'; CodePoints: '1F910'),
    (Name: 'zombie'; CodePoints: '1F9DF'),
    (Name: 'zombie_man'; CodePoints: '1F9DF 200D 2642 FE0F'),
    (Name: 'zombie_woman'; CodePoints: '1F9DF 200D 2640 FE0F'),
    (Name: 'zzz'; CodePoints: '1F4A4'));

class function TEmojiShortcodes.TryDecode(const Name: string; out Emoji: string): Boolean;
begin
  Emoji := '';

  var LowIndex := 0;
  var HighIndex := ShortcodeCount - 1;

  while LowIndex <= HighIndex do
  begin
    const MidIndex = (LowIndex + HighIndex) div 2;
    const Comparison = CompareStr(Name, Shortcodes[MidIndex].Name);

    if Comparison = 0 then
    begin
      Emoji := DecodeCodePoints(Shortcodes[MidIndex].CodePoints);
      Result := True;
      Exit;
    end;

    if Comparison < 0 then
      HighIndex := MidIndex - 1
    else
      LowIndex := MidIndex + 1;
  end;

  Result := False;
end;

class function TEmojiShortcodes.Count: Integer;
begin
  Result := ShortcodeCount;
end;

class function TEmojiShortcodes.NameAt(const Index: Integer): string;
begin
  Result := Shortcodes[Index].Name;
end;

class function TEmojiShortcodes.DecodeCodePoints(const CodePoints: string): string;
begin
  Result := '';

  for var HexDigits in CodePoints.Split([CodePointSeparator]) do
  begin
    const CodePoint = StrToInt(HexPrefix + HexDigits);
    Result := Result + Char.ConvertFromUtf32(CodePoint);
  end;
end;

end.
